name = "echo-mobile"
main = "cloudflare/src/index.ts"
compatibility_date = "2024-03-20"

# R2 Buckets configuration
[[r2_buckets]]
binding = "AVATARS_BUCKET"
bucket_name = "avatars"

[[r2_buckets]]
binding = "ECHO_MEDIA_BUCKET"
bucket_name = "echo-media"

[[r2_buckets]]
binding = "DM_MEDIA_BUCKET"
bucket_name = "dm-media"

[vars]
R2_ACCOUNT_ID = "5f35370a3c9265072a8ae6c47b22dd46"

[[r2_buckets]]
binding = "MINI_APP_MEDIA_BUCKET"
bucket_name = "mini-app-media"


[[r2_buckets]]
binding = "MARKETPLACE_PHOTOS_BUCKET"
bucket_name = "marketplace-photos"

