// Built-in food database for the Fitness mini-app. Curated, offline, no API.
// Values are per listed serving (approximate, rounded — good enough for
// day-to-day logging). Indian staples first-class alongside global basics.

export interface FoodItem {
  id: string;
  name: string;
  /** human serving label, e.g. "1 roti", "100 g", "1 cup" */
  serving: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  tags?: string[];
}

export type FoodGroupId = 'quick' | 'indian' | 'protein' | 'seafood' | 'veg' | 'breakfast' | 'snacks' | 'brands' | 'drinks' | 'fruit' | 'global';

export const FOOD_GROUPS: { id: FoodGroupId; label: string }[] = [
  { id: 'quick', label: 'Quick' },
  { id: 'indian', label: 'Indian' },
  { id: 'protein', label: 'Protein' },
  { id: 'seafood', label: 'Seafood' },
  { id: 'veg', label: 'Veggies' },
  { id: 'breakfast', label: 'Breakfast' },
  { id: 'snacks', label: 'Snacks' },
  { id: 'brands', label: 'Brands' },
  { id: 'drinks', label: 'Drinks' },
  { id: 'fruit', label: 'Fruit' },
  { id: 'global', label: 'Global' },
];

export const FOOD_DB: FoodItem[] = [
  // ── Indian staples ──
  { id: 'roti', name: 'Roti / Chapati', serving: '1 medium', calories: 100, protein: 3, carbs: 18, fat: 2 },
  { id: 'paratha', name: 'Plain Paratha', serving: '1 medium', calories: 180, protein: 4, carbs: 25, fat: 7 },
  { id: 'aloo-paratha', name: 'Aloo Paratha', serving: '1 medium', calories: 250, protein: 5, carbs: 35, fat: 10 },
  { id: 'naan', name: 'Butter Naan', serving: '1 piece', calories: 260, protein: 7, carbs: 40, fat: 8 },
  { id: 'rice-cooked', name: 'Rice (cooked)', serving: '1 cup', calories: 200, protein: 4, carbs: 45, fat: 0.5 },
  { id: 'jeera-rice', name: 'Jeera Rice', serving: '1 cup', calories: 250, protein: 4, carbs: 46, fat: 6 },
  { id: 'biryani-chicken', name: 'Chicken Biryani', serving: '1 plate', calories: 480, protein: 25, carbs: 55, fat: 17 },
  { id: 'biryani-veg', name: 'Veg Biryani', serving: '1 plate', calories: 400, protein: 9, carbs: 60, fat: 13 },
  { id: 'dal-tadka', name: 'Dal Tadka', serving: '1 bowl', calories: 180, protein: 9, carbs: 22, fat: 6 },
  { id: 'dal-makhani', name: 'Dal Makhani', serving: '1 bowl', calories: 280, protein: 11, carbs: 25, fat: 15 },
  { id: 'chole', name: 'Chole (chickpea curry)', serving: '1 bowl', calories: 250, protein: 11, carbs: 32, fat: 9 },
  { id: 'rajma', name: 'Rajma', serving: '1 bowl', calories: 230, protein: 12, carbs: 30, fat: 7 },
  { id: 'paneer-butter', name: 'Paneer Butter Masala', serving: '1 bowl', calories: 350, protein: 14, carbs: 12, fat: 27 },
  { id: 'palak-paneer', name: 'Palak Paneer', serving: '1 bowl', calories: 280, protein: 13, carbs: 10, fat: 21 },
  { id: 'paneer-raw', name: 'Paneer (raw)', serving: '100 g', calories: 265, protein: 18, carbs: 4, fat: 20 },
  { id: 'chicken-curry', name: 'Chicken Curry', serving: '1 bowl', calories: 280, protein: 25, carbs: 8, fat: 16 },
  { id: 'butter-chicken', name: 'Butter Chicken', serving: '1 bowl', calories: 430, protein: 27, carbs: 12, fat: 30 },
  { id: 'egg-curry', name: 'Egg Curry (2 eggs)', serving: '1 bowl', calories: 250, protein: 14, carbs: 8, fat: 18 },
  { id: 'idli', name: 'Idli', serving: '2 pieces', calories: 120, protein: 4, carbs: 25, fat: 0.5 },
  { id: 'dosa', name: 'Masala Dosa', serving: '1 piece', calories: 330, protein: 6, carbs: 50, fat: 11 },
  { id: 'sambar', name: 'Sambar', serving: '1 bowl', calories: 130, protein: 6, carbs: 18, fat: 4 },
  { id: 'poha', name: 'Poha', serving: '1 plate', calories: 250, protein: 5, carbs: 45, fat: 6 },
  { id: 'upma', name: 'Upma', serving: '1 plate', calories: 230, protein: 6, carbs: 38, fat: 7 },
  { id: 'khichdi', name: 'Khichdi', serving: '1 bowl', calories: 210, protein: 8, carbs: 35, fat: 5 },
  { id: 'curd', name: 'Curd / Dahi', serving: '1 cup', calories: 100, protein: 6, carbs: 8, fat: 5 },
  { id: 'raita', name: 'Raita', serving: '1 bowl', calories: 80, protein: 4, carbs: 7, fat: 4 },
  { id: 'samosa', name: 'Samosa', serving: '1 piece', calories: 260, protein: 4, carbs: 28, fat: 15 },
  { id: 'pakora', name: 'Pakora', serving: '5 pieces', calories: 230, protein: 5, carbs: 20, fat: 15 },
  { id: 'pav-bhaji', name: 'Pav Bhaji', serving: '1 plate', calories: 400, protein: 10, carbs: 55, fat: 16 },
  { id: 'chai', name: 'Chai (with milk & sugar)', serving: '1 cup', calories: 90, protein: 2, carbs: 12, fat: 3.5 },
  { id: 'lassi', name: 'Sweet Lassi', serving: '1 glass', calories: 220, protein: 6, carbs: 32, fat: 8 },
  { id: 'gulab-jamun', name: 'Gulab Jamun', serving: '1 piece', calories: 150, protein: 2, carbs: 22, fat: 6 },
  { id: 'jalebi', name: 'Jalebi', serving: '2 pieces', calories: 200, protein: 1, carbs: 32, fat: 8 },

  // ── Proteins ──
  { id: 'chicken-breast', name: 'Chicken Breast (grilled)', serving: '100 g', calories: 165, protein: 31, carbs: 0, fat: 3.6 },
  { id: 'chicken-thigh', name: 'Chicken Thigh (cooked)', serving: '100 g', calories: 210, protein: 26, carbs: 0, fat: 11 },
  { id: 'egg-boiled', name: 'Egg (boiled)', serving: '1 large', calories: 78, protein: 6, carbs: 0.6, fat: 5 },
  { id: 'egg-omelette', name: 'Omelette (2 eggs)', serving: '1 serving', calories: 220, protein: 14, carbs: 2, fat: 17 },
  { id: 'fish-grilled', name: 'Fish (grilled)', serving: '100 g', calories: 150, protein: 25, carbs: 0, fat: 5 },
  { id: 'mutton', name: 'Mutton (cooked)', serving: '100 g', calories: 260, protein: 25, carbs: 0, fat: 17 },
  { id: 'tofu', name: 'Tofu', serving: '100 g', calories: 76, protein: 8, carbs: 2, fat: 4.5 },
  { id: 'soya-chunks', name: 'Soya Chunks (dry)', serving: '50 g', calories: 170, protein: 26, carbs: 15, fat: 0.5 },
  { id: 'whey', name: 'Whey Protein (1 scoop)', serving: '30 g', calories: 120, protein: 24, carbs: 3, fat: 1.5 },
  { id: 'sprouts', name: 'Moong Sprouts', serving: '1 cup', calories: 60, protein: 6, carbs: 12, fat: 0.3 },

  // ── Dairy & breakfast ──
  { id: 'milk-full', name: 'Milk (full fat)', serving: '1 glass (250 ml)', calories: 150, protein: 8, carbs: 12, fat: 8 },
  { id: 'milk-toned', name: 'Milk (toned)', serving: '1 glass (250 ml)', calories: 120, protein: 8, carbs: 12, fat: 4 },
  { id: 'oats', name: 'Oats (with milk)', serving: '1 bowl', calories: 220, protein: 9, carbs: 34, fat: 6 },
  { id: 'muesli', name: 'Muesli', serving: '1 bowl', calories: 250, protein: 8, carbs: 42, fat: 6 },
  { id: 'cornflakes', name: 'Cornflakes (with milk)', serving: '1 bowl', calories: 200, protein: 6, carbs: 38, fat: 3 },
  { id: 'bread-white', name: 'Bread (white)', serving: '2 slices', calories: 140, protein: 5, carbs: 26, fat: 2 },
  { id: 'bread-brown', name: 'Bread (brown)', serving: '2 slices', calories: 130, protein: 6, carbs: 24, fat: 2 },
  { id: 'peanut-butter', name: 'Peanut Butter', serving: '1 tbsp', calories: 95, protein: 4, carbs: 3, fat: 8 },
  { id: 'ghee', name: 'Ghee', serving: '1 tsp', calories: 45, protein: 0, carbs: 0, fat: 5 },
  { id: 'cheese-slice', name: 'Cheese Slice', serving: '1 slice', calories: 70, protein: 4, carbs: 1, fat: 5.5 },

  // ── Fruits & veg ──
  { id: 'banana', name: 'Banana', serving: '1 medium', calories: 105, protein: 1.3, carbs: 27, fat: 0.4 },
  { id: 'apple', name: 'Apple', serving: '1 medium', calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
  { id: 'mango', name: 'Mango', serving: '1 cup', calories: 100, protein: 1.4, carbs: 25, fat: 0.6 },
  { id: 'orange', name: 'Orange', serving: '1 medium', calories: 62, protein: 1.2, carbs: 15, fat: 0.2 },
  { id: 'grapes', name: 'Grapes', serving: '1 cup', calories: 100, protein: 1, carbs: 27, fat: 0.2 },
  { id: 'papaya', name: 'Papaya', serving: '1 cup', calories: 55, protein: 0.9, carbs: 14, fat: 0.2 },
  { id: 'pomegranate', name: 'Pomegranate', serving: '1 cup', calories: 145, protein: 3, carbs: 33, fat: 2 },
  { id: 'cucumber-salad', name: 'Cucumber Salad', serving: '1 bowl', calories: 30, protein: 1.5, carbs: 6, fat: 0.2 },
  { id: 'mixed-veg', name: 'Mixed Veg Sabzi', serving: '1 bowl', calories: 150, protein: 4, carbs: 15, fat: 8 },
  { id: 'aloo-sabzi', name: 'Aloo Sabzi', serving: '1 bowl', calories: 190, protein: 3, carbs: 28, fat: 8 },
  { id: 'bhindi', name: 'Bhindi Fry', serving: '1 bowl', calories: 150, protein: 3, carbs: 12, fat: 10 },

  // ── Nuts & snacks ──
  { id: 'almonds', name: 'Almonds', serving: '10 pieces', calories: 70, protein: 2.6, carbs: 2.5, fat: 6 },
  { id: 'cashews', name: 'Cashews', serving: '10 pieces', calories: 90, protein: 3, carbs: 5, fat: 7 },
  { id: 'peanuts-roasted', name: 'Peanuts (roasted)', serving: '30 g', calories: 170, protein: 8, carbs: 5, fat: 14 },
  { id: 'walnuts', name: 'Walnuts', serving: '4 halves', calories: 105, protein: 2.4, carbs: 2, fat: 10 },
  { id: 'makhana', name: 'Makhana (roasted)', serving: '1 cup', calories: 106, protein: 3, carbs: 20, fat: 0.5 },
  { id: 'biscuits-marie', name: 'Marie Biscuits', serving: '4 pieces', calories: 110, protein: 2, carbs: 20, fat: 3 },
  { id: 'chips', name: 'Potato Chips', serving: '1 small pack (30 g)', calories: 160, protein: 2, carbs: 15, fat: 10 },
  { id: 'dark-chocolate', name: 'Dark Chocolate', serving: '2 squares (20 g)', calories: 110, protein: 1.5, carbs: 9, fat: 8 },

  // ── Global mains ──
  { id: 'pasta', name: 'Pasta (with sauce)', serving: '1 plate', calories: 380, protein: 12, carbs: 58, fat: 11 },
  { id: 'pizza-slice', name: 'Pizza', serving: '1 slice', calories: 280, protein: 11, carbs: 33, fat: 11 },
  { id: 'burger-veg', name: 'Veg Burger', serving: '1 burger', calories: 350, protein: 9, carbs: 45, fat: 15 },
  { id: 'burger-chicken', name: 'Chicken Burger', serving: '1 burger', calories: 420, protein: 22, carbs: 42, fat: 18 },
  { id: 'sandwich-veg', name: 'Veg Sandwich (grilled)', serving: '1 sandwich', calories: 260, protein: 8, carbs: 36, fat: 9 },
  { id: 'fried-rice', name: 'Veg Fried Rice', serving: '1 plate', calories: 350, protein: 7, carbs: 55, fat: 11 },
  { id: 'noodles', name: 'Hakka Noodles', serving: '1 plate', calories: 400, protein: 9, carbs: 58, fat: 14 },
  { id: 'momos-veg', name: 'Momos (veg, steamed)', serving: '6 pieces', calories: 210, protein: 6, carbs: 36, fat: 5 },
  { id: 'french-fries', name: 'French Fries', serving: '1 medium', calories: 340, protein: 4, carbs: 44, fat: 16 },
  { id: 'salad-chicken', name: 'Chicken Salad', serving: '1 bowl', calories: 280, protein: 26, carbs: 10, fat: 15 },

  // ── Drinks ──
  { id: 'coffee-milk', name: 'Coffee (with milk & sugar)', serving: '1 cup', calories: 80, protein: 2, carbs: 10, fat: 3 },
  { id: 'coffee-black', name: 'Black Coffee', serving: '1 cup', calories: 5, protein: 0.3, carbs: 0, fat: 0 },
  { id: 'juice-orange', name: 'Orange Juice', serving: '1 glass', calories: 110, protein: 2, carbs: 26, fat: 0.5 },
  { id: 'cola', name: 'Cola', serving: '1 can (330 ml)', calories: 140, protein: 0, carbs: 39, fat: 0 },
  { id: 'coconut-water', name: 'Coconut Water', serving: '1 glass', calories: 45, protein: 1.7, carbs: 9, fat: 0.5 },
  { id: 'buttermilk', name: 'Buttermilk / Chaas', serving: '1 glass', calories: 40, protein: 2, carbs: 5, fat: 1 },

  // ── More Indian breads, grains & bowls ──
  { id: 'phulka', name: 'Phulka', serving: '1 medium', calories: 80, protein: 3, carbs: 16, fat: 1 },
  { id: 'bajra-roti', name: 'Bajra Roti', serving: '1 medium', calories: 120, protein: 4, carbs: 22, fat: 2 },
  { id: 'jowar-roti', name: 'Jowar Roti', serving: '1 medium', calories: 110, protein: 3.5, carbs: 22, fat: 1.5 },
  { id: 'missi-roti', name: 'Missi Roti', serving: '1 medium', calories: 170, protein: 6, carbs: 27, fat: 5 },
  { id: 'rumali-roti', name: 'Rumali Roti', serving: '1 piece', calories: 160, protein: 5, carbs: 30, fat: 3 },
  { id: 'kulcha', name: 'Kulcha', serving: '1 piece', calories: 240, protein: 7, carbs: 42, fat: 6 },
  { id: 'appam', name: 'Appam', serving: '2 pieces', calories: 180, protein: 3, carbs: 38, fat: 2 },
  { id: 'puttu', name: 'Puttu', serving: '1 cup', calories: 210, protein: 5, carbs: 46, fat: 2 },
  { id: 'lemon-rice', name: 'Lemon Rice', serving: '1 cup', calories: 270, protein: 5, carbs: 48, fat: 7 },
  { id: 'curd-rice', name: 'Curd Rice', serving: '1 cup', calories: 220, protein: 7, carbs: 36, fat: 6 },
  { id: 'pulao-veg', name: 'Veg Pulao', serving: '1 plate', calories: 360, protein: 8, carbs: 58, fat: 11 },
  { id: 'quinoa-cooked', name: 'Quinoa (cooked)', serving: '1 cup', calories: 220, protein: 8, carbs: 39, fat: 3.5 },
  { id: 'millet-khichdi', name: 'Millet Khichdi', serving: '1 bowl', calories: 240, protein: 8, carbs: 42, fat: 5 },
  { id: 'brown-rice', name: 'Brown Rice', serving: '1 cup', calories: 215, protein: 5, carbs: 45, fat: 1.8 },

  // ── Indian curries, sabzis & regional meals ──
  { id: 'moong-dal', name: 'Moong Dal', serving: '1 bowl', calories: 150, protein: 10, carbs: 22, fat: 3 },
  { id: 'masoor-dal', name: 'Masoor Dal', serving: '1 bowl', calories: 165, protein: 11, carbs: 24, fat: 3 },
  { id: 'kadhi', name: 'Kadhi', serving: '1 bowl', calories: 170, protein: 6, carbs: 16, fat: 9 },
  { id: 'baingan-bharta', name: 'Baingan Bharta', serving: '1 bowl', calories: 150, protein: 3, carbs: 14, fat: 9 },
  { id: 'gobi-sabzi', name: 'Gobi Sabzi', serving: '1 bowl', calories: 120, protein: 4, carbs: 14, fat: 6 },
  { id: 'lauki-sabzi', name: 'Lauki Sabzi', serving: '1 bowl', calories: 90, protein: 3, carbs: 10, fat: 5 },
  { id: 'matar-paneer', name: 'Matar Paneer', serving: '1 bowl', calories: 320, protein: 15, carbs: 18, fat: 22 },
  { id: 'kadai-paneer', name: 'Kadai Paneer', serving: '1 bowl', calories: 360, protein: 16, carbs: 15, fat: 26 },
  { id: 'chicken-tikka', name: 'Chicken Tikka', serving: '6 pieces', calories: 280, protein: 34, carbs: 5, fat: 13 },
  { id: 'tandoori-chicken', name: 'Tandoori Chicken', serving: '1 leg quarter', calories: 320, protein: 38, carbs: 4, fat: 16 },
  { id: 'fish-curry', name: 'Fish Curry', serving: '1 bowl', calories: 260, protein: 26, carbs: 8, fat: 14 },
  { id: 'prawn-curry', name: 'Prawn Curry', serving: '1 bowl', calories: 240, protein: 28, carbs: 8, fat: 11 },
  { id: 'thali-veg', name: 'Veg Thali', serving: '1 plate', calories: 720, protein: 22, carbs: 105, fat: 24 },
  { id: 'thali-nonveg', name: 'Non-Veg Thali', serving: '1 plate', calories: 850, protein: 42, carbs: 95, fat: 34 },
  { id: 'sattu-drink', name: 'Sattu Drink', serving: '1 glass', calories: 160, protein: 8, carbs: 28, fat: 2 },

  // ── Breakfast & light meals ──
  { id: 'plain-dosa', name: 'Plain Dosa', serving: '1 piece', calories: 170, protein: 4, carbs: 30, fat: 4 },
  { id: 'uttapam', name: 'Uttapam', serving: '1 piece', calories: 260, protein: 7, carbs: 42, fat: 8 },
  { id: 'medu-vada', name: 'Medu Vada', serving: '2 pieces', calories: 260, protein: 8, carbs: 32, fat: 11 },
  { id: 'besan-chilla', name: 'Besan Chilla', serving: '2 pieces', calories: 220, protein: 12, carbs: 26, fat: 8 },
  { id: 'moong-chilla', name: 'Moong Dal Chilla', serving: '2 pieces', calories: 210, protein: 14, carbs: 28, fat: 5 },
  { id: 'dhokla', name: 'Dhokla', serving: '4 pieces', calories: 180, protein: 7, carbs: 32, fat: 3 },
  { id: 'thepla', name: 'Thepla', serving: '2 pieces', calories: 240, protein: 7, carbs: 36, fat: 8 },
  { id: 'egg-bhurji', name: 'Egg Bhurji', serving: '2 eggs', calories: 240, protein: 15, carbs: 5, fat: 18 },
  { id: 'scrambled-eggs', name: 'Scrambled Eggs', serving: '2 eggs', calories: 200, protein: 13, carbs: 2, fat: 15 },
  { id: 'greek-yogurt', name: 'Greek Yogurt', serving: '1 cup', calories: 130, protein: 20, carbs: 8, fat: 0 },
  { id: 'overnight-oats', name: 'Overnight Oats', serving: '1 jar', calories: 320, protein: 15, carbs: 48, fat: 9 },
  { id: 'protein-smoothie', name: 'Protein Smoothie', serving: '1 glass', calories: 300, protein: 25, carbs: 35, fat: 7 },
  { id: 'avocado-toast', name: 'Avocado Toast', serving: '1 toast', calories: 260, protein: 8, carbs: 28, fat: 14 },
  { id: 'pancakes', name: 'Pancakes', serving: '2 medium', calories: 350, protein: 9, carbs: 56, fat: 10 },

  // ── Lean proteins & fitness staples ──
  { id: 'egg-white', name: 'Egg Whites', serving: '4 whites', calories: 68, protein: 14, carbs: 1, fat: 0 },
  { id: 'turkey-breast', name: 'Turkey Breast', serving: '100 g', calories: 135, protein: 30, carbs: 0, fat: 1.5 },
  { id: 'salmon', name: 'Salmon', serving: '100 g', calories: 208, protein: 22, carbs: 0, fat: 13 },
  { id: 'tuna', name: 'Tuna', serving: '100 g', calories: 132, protein: 29, carbs: 0, fat: 1 },
  { id: 'shrimp', name: 'Shrimp', serving: '100 g', calories: 99, protein: 24, carbs: 0.2, fat: 0.3 },
  { id: 'lean-beef', name: 'Lean Beef', serving: '100 g', calories: 217, protein: 26, carbs: 0, fat: 12 },
  { id: 'chickpeas-boiled', name: 'Chickpeas (boiled)', serving: '1 cup', calories: 270, protein: 15, carbs: 45, fat: 4 },
  { id: 'black-beans', name: 'Black Beans', serving: '1 cup', calories: 227, protein: 15, carbs: 41, fat: 1 },
  { id: 'lentils-boiled', name: 'Lentils (boiled)', serving: '1 cup', calories: 230, protein: 18, carbs: 40, fat: 1 },
  { id: 'tempeh', name: 'Tempeh', serving: '100 g', calories: 195, protein: 20, carbs: 8, fat: 11 },
  { id: 'cottage-cheese', name: 'Cottage Cheese', serving: '1 cup', calories: 220, protein: 28, carbs: 6, fat: 10 },
  { id: 'protein-bar', name: 'Protein Bar', serving: '1 bar', calories: 220, protein: 20, carbs: 22, fat: 7 },

  // ── Fruits, vegetables & salads ──
  { id: 'watermelon', name: 'Watermelon', serving: '2 cups', calories: 90, protein: 2, carbs: 23, fat: 0 },
  { id: 'strawberries', name: 'Strawberries', serving: '1 cup', calories: 50, protein: 1, carbs: 12, fat: 0.5 },
  { id: 'blueberries', name: 'Blueberries', serving: '1 cup', calories: 85, protein: 1, carbs: 21, fat: 0.5 },
  { id: 'kiwi', name: 'Kiwi', serving: '2 pieces', calories: 90, protein: 2, carbs: 22, fat: 1 },
  { id: 'pear', name: 'Pear', serving: '1 medium', calories: 100, protein: 1, carbs: 27, fat: 0 },
  { id: 'guava', name: 'Guava', serving: '1 medium', calories: 68, protein: 2.6, carbs: 14, fat: 1 },
  { id: 'dates', name: 'Dates', serving: '3 pieces', calories: 200, protein: 2, carbs: 54, fat: 0 },
  { id: 'spinach', name: 'Spinach', serving: '1 cup cooked', calories: 40, protein: 5, carbs: 7, fat: 0.5 },
  { id: 'broccoli', name: 'Broccoli', serving: '1 cup', calories: 55, protein: 4, carbs: 11, fat: 0.5 },
  { id: 'sweet-potato', name: 'Sweet Potato', serving: '1 medium', calories: 115, protein: 2, carbs: 27, fat: 0 },
  { id: 'boiled-potato', name: 'Potato (boiled)', serving: '1 medium', calories: 160, protein: 4, carbs: 37, fat: 0 },
  { id: 'corn-cob', name: 'Corn on the Cob', serving: '1 cob', calories: 120, protein: 4, carbs: 27, fat: 1.5 },
  { id: 'green-salad', name: 'Green Salad', serving: '1 bowl', calories: 80, protein: 3, carbs: 12, fat: 3 },
  { id: 'sprout-salad', name: 'Sprout Salad', serving: '1 bowl', calories: 140, protein: 9, carbs: 24, fat: 2 },

  // ── Snacks, sweets & street food ──
  { id: 'bhel-puri', name: 'Bhel Puri', serving: '1 plate', calories: 220, protein: 6, carbs: 42, fat: 4 },
  { id: 'pani-puri', name: 'Pani Puri', serving: '6 pieces', calories: 180, protein: 4, carbs: 34, fat: 4 },
  { id: 'sev-puri', name: 'Sev Puri', serving: '6 pieces', calories: 300, protein: 7, carbs: 42, fat: 12 },
  { id: 'vada-pav', name: 'Vada Pav', serving: '1 piece', calories: 300, protein: 7, carbs: 45, fat: 11 },
  { id: 'kathi-roll-paneer', name: 'Paneer Kathi Roll', serving: '1 roll', calories: 430, protein: 17, carbs: 48, fat: 19 },
  { id: 'kathi-roll-chicken', name: 'Chicken Kathi Roll', serving: '1 roll', calories: 480, protein: 28, carbs: 48, fat: 20 },
  { id: 'dabeli', name: 'Dabeli', serving: '1 piece', calories: 310, protein: 8, carbs: 48, fat: 10 },
  { id: 'khandvi', name: 'Khandvi', serving: '6 pieces', calories: 160, protein: 7, carbs: 20, fat: 6 },
  { id: 'protein-makhana', name: 'Makhana Chaat', serving: '1 bowl', calories: 180, protein: 6, carbs: 28, fat: 5 },
  { id: 'trail-mix', name: 'Trail Mix', serving: '30 g', calories: 150, protein: 5, carbs: 14, fat: 9 },
  { id: 'popcorn', name: 'Popcorn', serving: '3 cups', calories: 100, protein: 3, carbs: 19, fat: 1.5 },
  { id: 'ice-cream', name: 'Ice Cream', serving: '1 scoop', calories: 140, protein: 3, carbs: 18, fat: 7 },
  { id: 'kheer', name: 'Kheer', serving: '1 bowl', calories: 260, protein: 7, carbs: 42, fat: 8 },
  { id: 'rasgulla', name: 'Rasgulla', serving: '1 piece', calories: 125, protein: 2, carbs: 25, fat: 1 },

  // ── Global meals ──
  { id: 'chicken-wrap', name: 'Chicken Wrap', serving: '1 wrap', calories: 420, protein: 28, carbs: 42, fat: 16 },
  { id: 'paneer-wrap', name: 'Paneer Wrap', serving: '1 wrap', calories: 450, protein: 20, carbs: 46, fat: 21 },
  { id: 'burrito-bowl', name: 'Burrito Bowl', serving: '1 bowl', calories: 650, protein: 32, carbs: 78, fat: 22 },
  { id: 'sushi', name: 'Sushi Rolls', serving: '8 pieces', calories: 320, protein: 14, carbs: 58, fat: 5 },
  { id: 'ramen', name: 'Ramen', serving: '1 bowl', calories: 520, protein: 20, carbs: 70, fat: 18 },
  { id: 'pho', name: 'Pho', serving: '1 bowl', calories: 420, protein: 25, carbs: 60, fat: 10 },
  { id: 'tacos-chicken', name: 'Chicken Tacos', serving: '2 tacos', calories: 360, protein: 24, carbs: 38, fat: 13 },
  { id: 'falafel-bowl', name: 'Falafel Bowl', serving: '1 bowl', calories: 560, protein: 18, carbs: 68, fat: 24 },
  { id: 'hummus', name: 'Hummus', serving: '3 tbsp', calories: 100, protein: 4, carbs: 8, fat: 6 },
  { id: 'caesar-salad', name: 'Caesar Salad', serving: '1 bowl', calories: 330, protein: 12, carbs: 14, fat: 25 },
  { id: 'grilled-cheese', name: 'Grilled Cheese Sandwich', serving: '1 sandwich', calories: 380, protein: 14, carbs: 36, fat: 21 },
  { id: 'tomato-soup', name: 'Tomato Soup', serving: '1 bowl', calories: 120, protein: 3, carbs: 22, fat: 3 },

  // ── Drinks & hydration ──
  { id: 'green-tea', name: 'Green Tea', serving: '1 cup', calories: 2, protein: 0, carbs: 0, fat: 0 },
  { id: 'lemon-water', name: 'Lemon Water', serving: '1 glass', calories: 10, protein: 0, carbs: 3, fat: 0 },
  { id: 'electrolyte-drink', name: 'Electrolyte Drink', serving: '1 bottle', calories: 60, protein: 0, carbs: 15, fat: 0 },
  { id: 'sports-drink', name: 'Sports Drink', serving: '1 bottle', calories: 130, protein: 0, carbs: 34, fat: 0 },
  { id: 'sugarcane-juice', name: 'Sugarcane Juice', serving: '1 glass', calories: 180, protein: 0, carbs: 44, fat: 0 },
  { id: 'smoothie-fruit', name: 'Fruit Smoothie', serving: '1 glass', calories: 240, protein: 6, carbs: 48, fat: 3 },
  { id: 'cold-coffee', name: 'Cold Coffee', serving: '1 glass', calories: 210, protein: 6, carbs: 32, fat: 7 },
  { id: 'beer', name: 'Beer', serving: '1 pint', calories: 200, protein: 2, carbs: 15, fat: 0 },

  // ── Seafood ──
  { id: 'salmon-smoked', name: 'Smoked Salmon', serving: '50 g', calories: 117, protein: 18, carbs: 0, fat: 4, tags: ['seafood'] },
  { id: 'tuna-canned', name: 'Tuna (canned in water)', serving: '100 g', calories: 116, protein: 26, carbs: 0, fat: 1, tags: ['seafood'] },
  { id: 'tuna-steak', name: 'Tuna Steak (grilled)', serving: '100 g', calories: 130, protein: 28, carbs: 0, fat: 1, tags: ['seafood'] },
  { id: 'cod-baked', name: 'Cod (baked)', serving: '100 g', calories: 105, protein: 23, carbs: 0, fat: 1, tags: ['seafood'] },
  { id: 'tilapia', name: 'Tilapia (grilled)', serving: '100 g', calories: 128, protein: 26, carbs: 0, fat: 3, tags: ['seafood'] },
  { id: 'mackerel', name: 'Mackerel (cooked)', serving: '100 g', calories: 262, protein: 24, carbs: 0, fat: 18, tags: ['seafood'] },
  { id: 'sardines', name: 'Sardines (canned)', serving: '100 g', calories: 208, protein: 25, carbs: 0, fat: 11, tags: ['seafood'] },
  { id: 'trout', name: 'Trout (cooked)', serving: '100 g', calories: 168, protein: 24, carbs: 0, fat: 7, tags: ['seafood'] },
  { id: 'haddock', name: 'Haddock (cooked)', serving: '100 g', calories: 116, protein: 25, carbs: 0, fat: 1, tags: ['seafood'] },
  { id: 'snapper', name: 'Red Snapper (cooked)', serving: '100 g', calories: 128, protein: 26, carbs: 0, fat: 2, tags: ['seafood'] },
  { id: 'basa-grilled', name: 'Basa (grilled)', serving: '100 g', calories: 90, protein: 15, carbs: 0, fat: 3, tags: ['seafood'] },
  { id: 'pomfret-fry', name: 'Pomfret Fry', serving: '1 piece', calories: 200, protein: 22, carbs: 4, fat: 11, tags: ['seafood'] },
  { id: 'surmai-fry', name: 'Surmai / Kingfish Fry', serving: '1 piece', calories: 230, protein: 24, carbs: 5, fat: 12, tags: ['seafood'] },
  { id: 'hilsa-curry', name: 'Hilsa Fish Curry', serving: '1 bowl', calories: 300, protein: 22, carbs: 6, fat: 20, tags: ['seafood'] },
  { id: 'shrimp-fried', name: 'Fried Shrimp', serving: '100 g', calories: 240, protein: 18, carbs: 12, fat: 12, tags: ['seafood'] },
  { id: 'crab-cooked', name: 'Crab (cooked)', serving: '100 g', calories: 97, protein: 19, carbs: 0, fat: 1.5, tags: ['seafood'] },
  { id: 'lobster', name: 'Lobster (cooked)', serving: '100 g', calories: 89, protein: 19, carbs: 0, fat: 0.9, tags: ['seafood'] },
  { id: 'squid-grilled', name: 'Squid / Calamari (grilled)', serving: '100 g', calories: 92, protein: 16, carbs: 3, fat: 1.4, tags: ['seafood'] },
  { id: 'calamari-fried', name: 'Fried Calamari', serving: '100 g', calories: 175, protein: 15, carbs: 8, fat: 7, tags: ['seafood'] },
  { id: 'oysters', name: 'Oysters', serving: '6 pieces', calories: 50, protein: 5, carbs: 3, fat: 1.5, tags: ['seafood'] },
  { id: 'mussels', name: 'Mussels (cooked)', serving: '100 g', calories: 172, protein: 24, carbs: 7, fat: 4.5, tags: ['seafood'] },
  { id: 'clams', name: 'Clams (cooked)', serving: '100 g', calories: 148, protein: 26, carbs: 5, fat: 2, tags: ['seafood'] },
  { id: 'scallops', name: 'Scallops (cooked)', serving: '100 g', calories: 137, protein: 24, carbs: 6, fat: 1, tags: ['seafood'] },
  { id: 'fish-fingers', name: 'Fish Fingers', serving: '3 pieces', calories: 190, protein: 9, carbs: 18, fat: 9, tags: ['seafood', 'brand'] },
  { id: 'fish-and-chips', name: 'Fish & Chips', serving: '1 serving', calories: 600, protein: 30, carbs: 55, fat: 30, tags: ['seafood'] },
  { id: 'prawn-masala', name: 'Prawn Masala', serving: '1 bowl', calories: 260, protein: 22, carbs: 10, fat: 14, tags: ['seafood'] },
  { id: 'fish-fry-indian', name: 'Fish Fry (Indian)', serving: '1 piece', calories: 220, protein: 18, carbs: 6, fat: 13, tags: ['seafood'] },
  { id: 'fish-tikka', name: 'Fish Tikka', serving: '100 g', calories: 180, protein: 25, carbs: 3, fat: 7, tags: ['seafood'] },
  { id: 'prawn-biryani', name: 'Prawn Biryani', serving: '1 plate', calories: 450, protein: 24, carbs: 55, fat: 15, tags: ['seafood'] },
  { id: 'rohu-curry', name: 'Rohu Fish Curry', serving: '1 bowl', calories: 230, protein: 20, carbs: 7, fat: 13, tags: ['seafood'] },
  { id: 'salmon-sushi', name: 'Salmon Sushi', serving: '6 pieces', calories: 250, protein: 9, carbs: 38, fat: 6, tags: ['seafood'] },
  { id: 'crab-cakes', name: 'Crab Cakes', serving: '2 cakes', calories: 260, protein: 18, carbs: 14, fat: 15, tags: ['seafood'] },

  // ── Brands, fast food & commercial ──
  { id: 'mc-aloo-tikki', name: "McDonald's McAloo Tikki", serving: '1 burger', calories: 340, protein: 9, carbs: 50, fat: 12, tags: ['brand', 'mcdonalds'] },
  { id: 'mc-veggie', name: "McDonald's McVeggie", serving: '1 burger', calories: 400, protein: 11, carbs: 55, fat: 15, tags: ['brand', 'mcdonalds'] },
  { id: 'mc-chicken', name: "McDonald's McChicken", serving: '1 burger', calories: 400, protein: 14, carbs: 40, fat: 21, tags: ['brand', 'mcdonalds'] },
  { id: 'mc-spicy-paneer', name: "McDonald's McSpicy Paneer", serving: '1 burger', calories: 650, protein: 18, carbs: 60, fat: 37, tags: ['brand', 'mcdonalds'] },
  { id: 'big-mac', name: "McDonald's Big Mac", serving: '1 burger', calories: 550, protein: 25, carbs: 45, fat: 30, tags: ['brand', 'mcdonalds'] },
  { id: 'mc-fries', name: "McDonald's Fries (medium)", serving: '1 medium', calories: 340, protein: 4, carbs: 44, fat: 16, tags: ['brand', 'mcdonalds'] },
  { id: 'mc-flurry', name: "McDonald's McFlurry", serving: '1 regular', calories: 340, protein: 8, carbs: 52, fat: 11, tags: ['brand', 'mcdonalds'] },
  { id: 'kfc-chicken', name: 'KFC Fried Chicken', serving: '1 piece', calories: 290, protein: 20, carbs: 9, fat: 20, tags: ['brand', 'kfc'] },
  { id: 'kfc-zinger', name: 'KFC Zinger Burger', serving: '1 burger', calories: 450, protein: 24, carbs: 42, fat: 21, tags: ['brand', 'kfc'] },
  { id: 'kfc-popcorn', name: 'KFC Popcorn Chicken', serving: '1 regular', calories: 285, protein: 16, carbs: 20, fat: 16, tags: ['brand', 'kfc'] },
  { id: 'kfc-wings', name: 'KFC Hot Wings', serving: '5 pieces', calories: 380, protein: 22, carbs: 15, fat: 26, tags: ['brand', 'kfc'] },
  { id: 'bk-whopper', name: 'Burger King Whopper', serving: '1 burger', calories: 660, protein: 28, carbs: 49, fat: 40, tags: ['brand', 'burger king'] },
  { id: 'dominos-margherita', name: "Domino's Margherita (slice)", serving: '1 slice', calories: 200, protein: 8, carbs: 26, fat: 7, tags: ['brand', 'dominos', 'pizza'] },
  { id: 'dominos-pepperoni', name: "Domino's Pepperoni (slice)", serving: '1 slice', calories: 230, protein: 10, carbs: 25, fat: 10, tags: ['brand', 'dominos', 'pizza'] },
  { id: 'dominos-farmhouse', name: "Domino's Farmhouse (slice)", serving: '1 slice', calories: 220, protein: 9, carbs: 27, fat: 8, tags: ['brand', 'dominos', 'pizza'] },
  { id: 'dominos-garlic-bread', name: "Domino's Garlic Bread", serving: '2 pieces', calories: 150, protein: 4, carbs: 20, fat: 6, tags: ['brand', 'dominos'] },
  { id: 'pizzahut-pan', name: 'Pizza Hut Pan Pizza (slice)', serving: '1 slice', calories: 250, protein: 10, carbs: 28, fat: 11, tags: ['brand', 'pizza hut', 'pizza'] },
  { id: 'subway-veggie', name: 'Subway Veggie Delite (6")', serving: '6 inch', calories: 230, protein: 9, carbs: 44, fat: 3, tags: ['brand', 'subway'] },
  { id: 'subway-chicken-teriyaki', name: 'Subway Chicken Teriyaki (6")', serving: '6 inch', calories: 370, protein: 26, carbs: 47, fat: 8, tags: ['brand', 'subway'] },
  { id: 'subway-turkey', name: 'Subway Turkey (6")', serving: '6 inch', calories: 280, protein: 18, carbs: 46, fat: 4, tags: ['brand', 'subway'] },
  { id: 'sb-latte', name: 'Starbucks Caffe Latte (grande)', serving: '16 oz', calories: 190, protein: 13, carbs: 19, fat: 7, tags: ['brand', 'starbucks'] },
  { id: 'sb-cappuccino', name: 'Starbucks Cappuccino (grande)', serving: '16 oz', calories: 140, protein: 9, carbs: 14, fat: 5, tags: ['brand', 'starbucks'] },
  { id: 'sb-caramel-frap', name: 'Starbucks Caramel Frappuccino', serving: '16 oz', calories: 380, protein: 5, carbs: 60, fat: 15, tags: ['brand', 'starbucks'] },
  { id: 'dunkin-donut', name: 'Dunkin Glazed Donut', serving: '1 donut', calories: 260, protein: 4, carbs: 31, fat: 14, tags: ['brand', 'dunkin'] },
  { id: 'tacobell-taco', name: 'Taco Bell Crunchy Taco', serving: '1 taco', calories: 170, protein: 8, carbs: 13, fat: 9, tags: ['brand', 'taco bell'] },
  { id: 'tacobell-burrito', name: 'Taco Bell Bean Burrito', serving: '1 burrito', calories: 380, protein: 14, carbs: 55, fat: 11, tags: ['brand', 'taco bell'] },
  { id: 'maggi', name: 'Maggi Noodles', serving: '1 pack', calories: 350, protein: 8, carbs: 50, fat: 13, tags: ['brand', 'maggi'] },
  { id: 'instant-noodles', name: 'Instant Ramen Noodles', serving: '1 pack', calories: 380, protein: 8, carbs: 52, fat: 15, tags: ['brand'] },
  { id: 'lays-classic', name: "Lay's Chips (small pack)", serving: '30 g', calories: 160, protein: 2, carbs: 15, fat: 10, tags: ['brand', 'lays', 'chips'] },
  { id: 'kurkure', name: 'Kurkure', serving: '1 pack', calories: 190, protein: 3, carbs: 22, fat: 11, tags: ['brand', 'chips'] },
  { id: 'haldiram-bhujia', name: "Haldiram's Bhujia", serving: '30 g', calories: 170, protein: 5, carbs: 12, fat: 11, tags: ['brand', 'haldiram'] },
  { id: 'oreo', name: 'Oreo Cookies', serving: '3 cookies', calories: 160, protein: 1, carbs: 25, fat: 7, tags: ['brand', 'oreo'] },
  { id: 'parle-g', name: 'Parle-G Biscuits', serving: '5 biscuits', calories: 130, protein: 2, carbs: 22, fat: 4, tags: ['brand', 'parle'] },
  { id: 'good-day', name: 'Britannia Good Day', serving: '3 cookies', calories: 150, protein: 2, carbs: 20, fat: 7, tags: ['brand', 'britannia'] },
  { id: 'kitkat', name: 'KitKat (4 finger)', serving: '1 bar', calories: 210, protein: 3, carbs: 27, fat: 11, tags: ['brand', 'nestle'] },
  { id: 'dairy-milk', name: 'Cadbury Dairy Milk', serving: '1 small bar', calories: 250, protein: 3, carbs: 28, fat: 14, tags: ['brand', 'cadbury'] },
  { id: 'snickers', name: 'Snickers', serving: '1 bar', calories: 250, protein: 4, carbs: 33, fat: 12, tags: ['brand', 'mars'] },
  { id: 'nutella', name: 'Nutella', serving: '1 tbsp', calories: 100, protein: 1, carbs: 11, fat: 6, tags: ['brand', 'nutella'] },
  { id: 'amul-butter', name: 'Amul Butter', serving: '1 tbsp', calories: 90, protein: 0, carbs: 0, fat: 10, tags: ['brand', 'amul'] },
  { id: 'amul-cheese', name: 'Amul Cheese Slice', serving: '1 slice', calories: 60, protein: 4, carbs: 1, fat: 5, tags: ['brand', 'amul'] },
  { id: 'kelloggs-cornflakes', name: "Kellogg's Corn Flakes", serving: '1 cup', calories: 100, protein: 2, carbs: 24, fat: 0, tags: ['brand', 'kelloggs'] },
  { id: 'chocos', name: "Kellogg's Chocos", serving: '1 cup', calories: 120, protein: 2, carbs: 26, fat: 1, tags: ['brand', 'kelloggs'] },
  { id: 'coca-cola', name: 'Coca-Cola', serving: '330 ml can', calories: 140, protein: 0, carbs: 39, fat: 0, tags: ['brand', 'coca cola', 'cola'] },
  { id: 'pepsi', name: 'Pepsi', serving: '330 ml can', calories: 150, protein: 0, carbs: 41, fat: 0, tags: ['brand', 'pepsi', 'cola'] },
  { id: 'sprite', name: 'Sprite', serving: '330 ml can', calories: 140, protein: 0, carbs: 38, fat: 0, tags: ['brand'] },
  { id: 'diet-coke', name: 'Diet Coke', serving: '330 ml can', calories: 1, protein: 0, carbs: 0, fat: 0, tags: ['brand', 'coca cola'] },
  { id: 'red-bull', name: 'Red Bull', serving: '250 ml can', calories: 110, protein: 0, carbs: 28, fat: 0, tags: ['brand', 'red bull'] },
  { id: 'gatorade', name: 'Gatorade', serving: '500 ml', calories: 130, protein: 0, carbs: 34, fat: 0, tags: ['brand', 'gatorade'] },
  { id: 'monster-energy', name: 'Monster Energy', serving: '500 ml can', calories: 210, protein: 0, carbs: 54, fat: 0, tags: ['brand'] },
  { id: 'protein-bar-brand', name: 'Protein Bar (branded)', serving: '1 bar', calories: 200, protein: 20, carbs: 22, fat: 7, tags: ['brand', 'protein'] },
  { id: 'whey-shake-brand', name: 'Whey Protein Shake', serving: '1 scoop', calories: 120, protein: 24, carbs: 3, fat: 1.5, tags: ['brand', 'protein', 'whey'] },
  { id: 'yakult', name: 'Yakult', serving: '1 bottle', calories: 50, protein: 1, carbs: 12, fat: 0, tags: ['brand'] },
  { id: 'bournvita', name: 'Bournvita (with milk)', serving: '1 glass', calories: 180, protein: 7, carbs: 26, fat: 5, tags: ['brand', 'cadbury'] },

  // ── Italian ──
  { id: 'spaghetti-bolognese', name: 'Spaghetti Bolognese', serving: '1 plate', calories: 520, protein: 24, carbs: 60, fat: 20, tags: ['pasta', 'italian'] },
  { id: 'spaghetti-carbonara', name: 'Spaghetti Carbonara', serving: '1 plate', calories: 580, protein: 22, carbs: 62, fat: 27, tags: ['pasta', 'italian'] },
  { id: 'penne-arrabiata', name: 'Penne Arrabiata', serving: '1 plate', calories: 420, protein: 12, carbs: 68, fat: 11, tags: ['pasta', 'italian'] },
  { id: 'fettuccine-alfredo', name: 'Fettuccine Alfredo', serving: '1 plate', calories: 620, protein: 18, carbs: 66, fat: 31, tags: ['pasta', 'alfredo', 'italian'] },
  { id: 'lasagna', name: 'Lasagna', serving: '1 slice', calories: 400, protein: 22, carbs: 35, fat: 20, tags: ['italian'] },
  { id: 'mushroom-risotto', name: 'Mushroom Risotto', serving: '1 bowl', calories: 430, protein: 10, carbs: 62, fat: 15, tags: ['risotto', 'italian'] },
  { id: 'gnocchi', name: 'Gnocchi', serving: '1 plate', calories: 380, protein: 9, carbs: 68, fat: 8, tags: ['italian'] },
  { id: 'ravioli', name: 'Cheese Ravioli', serving: '1 plate', calories: 400, protein: 16, carbs: 52, fat: 14, tags: ['pasta', 'italian'] },
  { id: 'bruschetta', name: 'Bruschetta', serving: '2 pieces', calories: 190, protein: 5, carbs: 26, fat: 7, tags: ['italian'] },
  { id: 'minestrone-soup', name: 'Minestrone Soup', serving: '1 bowl', calories: 150, protein: 6, carbs: 24, fat: 4, tags: ['soup', 'italian'] },
  { id: 'tiramisu', name: 'Tiramisu', serving: '1 slice', calories: 320, protein: 6, carbs: 34, fat: 18, tags: ['italian', 'dessert'] },
  { id: 'gelato', name: 'Gelato', serving: '1 scoop', calories: 160, protein: 3, carbs: 24, fat: 6, tags: ['italian', 'dessert'] },
  { id: 'focaccia', name: 'Focaccia', serving: '1 piece', calories: 250, protein: 6, carbs: 34, fat: 10, tags: ['bread', 'italian'] },

  // ── Chinese & Indo-Chinese ──
  { id: 'veg-fried-rice', name: 'Veg Fried Rice', serving: '1 plate', calories: 350, protein: 8, carbs: 58, fat: 10, tags: ['rice', 'chinese'] },
  { id: 'chicken-fried-rice', name: 'Chicken Fried Rice', serving: '1 plate', calories: 420, protein: 20, carbs: 56, fat: 13, tags: ['rice', 'chinese'] },
  { id: 'hakka-noodles', name: 'Hakka Noodles', serving: '1 plate', calories: 380, protein: 10, carbs: 60, fat: 11, tags: ['noodles', 'hakka', 'chinese'] },
  { id: 'chicken-manchurian', name: 'Chicken Manchurian', serving: '1 bowl', calories: 340, protein: 22, carbs: 24, fat: 17, tags: ['manchurian', 'chinese'] },
  { id: 'veg-manchurian', name: 'Veg Manchurian', serving: '1 bowl', calories: 300, protein: 8, carbs: 34, fat: 14, tags: ['manchurian', 'chinese'] },
  { id: 'chilli-chicken', name: 'Chilli Chicken', serving: '1 bowl', calories: 360, protein: 26, carbs: 18, fat: 20, tags: ['chinese'] },
  { id: 'chilli-paneer', name: 'Chilli Paneer', serving: '1 bowl', calories: 340, protein: 16, carbs: 18, fat: 22, tags: ['chinese'] },
  { id: 'veg-spring-rolls', name: 'Veg Spring Rolls', serving: '2 pieces', calories: 200, protein: 5, carbs: 26, fat: 9, tags: ['chinese'] },
  { id: 'kung-pao-chicken', name: 'Kung Pao Chicken', serving: '1 bowl', calories: 380, protein: 27, carbs: 16, fat: 23, tags: ['chinese'] },
  { id: 'sweet-sour-chicken', name: 'Sweet & Sour Chicken', serving: '1 bowl', calories: 400, protein: 24, carbs: 40, fat: 15, tags: ['chinese'] },
  { id: 'chow-mein', name: 'Chicken Chow Mein', serving: '1 plate', calories: 430, protein: 20, carbs: 55, fat: 15, tags: ['noodles', 'chow', 'chinese'] },
  { id: 'wonton-soup', name: 'Wonton Soup', serving: '1 bowl', calories: 180, protein: 12, carbs: 20, fat: 6, tags: ['soup', 'chinese'] },
  { id: 'dim-sum', name: 'Steamed Dim Sum', serving: '4 pieces', calories: 220, protein: 12, carbs: 26, fat: 8, tags: ['dumpling', 'chinese'] },
  { id: 'honey-chilli-potato', name: 'Honey Chilli Potato', serving: '1 plate', calories: 340, protein: 5, carbs: 52, fat: 13, tags: ['chinese'] },

  // ── Thai ──
  { id: 'pad-thai', name: 'Pad Thai', serving: '1 plate', calories: 480, protein: 20, carbs: 62, fat: 17, tags: ['noodles', 'pad thai', 'thai'] },
  { id: 'thai-green-curry', name: 'Thai Green Curry', serving: '1 bowl', calories: 380, protein: 18, carbs: 22, fat: 25, tags: ['curry', 'thai'] },
  { id: 'thai-red-curry', name: 'Thai Red Curry', serving: '1 bowl', calories: 400, protein: 18, carbs: 24, fat: 26, tags: ['curry', 'thai'] },
  { id: 'tom-yum-soup', name: 'Tom Yum Soup', serving: '1 bowl', calories: 130, protein: 12, carbs: 12, fat: 4, tags: ['soup', 'thai'] },
  { id: 'thai-fried-rice', name: 'Thai Fried Rice', serving: '1 plate', calories: 400, protein: 14, carbs: 60, fat: 12, tags: ['rice', 'thai'] },
  { id: 'mango-sticky-rice', name: 'Mango Sticky Rice', serving: '1 serving', calories: 350, protein: 5, carbs: 68, fat: 8, tags: ['thai', 'dessert'] },
  { id: 'chicken-satay', name: 'Chicken Satay', serving: '4 skewers', calories: 280, protein: 28, carbs: 8, fat: 15, tags: ['satay', 'thai'] },

  // ── Japanese ──
  { id: 'ramen-bowl', name: 'Ramen (bowl)', serving: '1 bowl', calories: 450, protein: 20, carbs: 58, fat: 15, tags: ['ramen', 'noodles', 'japanese'] },
  { id: 'udon-noodles', name: 'Udon Noodles', serving: '1 bowl', calories: 380, protein: 12, carbs: 70, fat: 6, tags: ['udon', 'noodles', 'japanese'] },
  { id: 'chicken-teriyaki-jp', name: 'Chicken Teriyaki', serving: '1 plate', calories: 380, protein: 30, carbs: 28, fat: 15, tags: ['teriyaki', 'japanese'] },
  { id: 'tempura', name: 'Vegetable Tempura', serving: '6 pieces', calories: 320, protein: 6, carbs: 34, fat: 18, tags: ['tempura', 'japanese'] },
  { id: 'miso-soup', name: 'Miso Soup', serving: '1 bowl', calories: 70, protein: 6, carbs: 7, fat: 2, tags: ['soup', 'japanese'] },
  { id: 'edamame', name: 'Edamame', serving: '1 cup', calories: 190, protein: 17, carbs: 15, fat: 8, tags: ['japanese'] },
  { id: 'gyoza', name: 'Gyoza (dumplings)', serving: '5 pieces', calories: 250, protein: 12, carbs: 26, fat: 11, tags: ['gyoza', 'dumpling', 'japanese'] },
  { id: 'chicken-katsu', name: 'Chicken Katsu', serving: '1 plate', calories: 480, protein: 30, carbs: 40, fat: 22, tags: ['katsu', 'japanese'] },
  { id: 'veg-sushi', name: 'Veg Sushi Roll', serving: '6 pieces', calories: 200, protein: 5, carbs: 42, fat: 2, tags: ['sushi', 'japanese'] },
  { id: 'mochi', name: 'Mochi', serving: '2 pieces', calories: 190, protein: 2, carbs: 42, fat: 2, tags: ['japanese', 'dessert'] },

  // ── Korean ──
  { id: 'bibimbap', name: 'Bibimbap', serving: '1 bowl', calories: 490, protein: 20, carbs: 68, fat: 14, tags: ['bibimbap', 'rice', 'korean'] },
  { id: 'kimchi', name: 'Kimchi', serving: '1/2 cup', calories: 25, protein: 2, carbs: 4, fat: 0, tags: ['kimchi', 'korean'] },
  { id: 'bulgogi', name: 'Beef Bulgogi', serving: '1 plate', calories: 400, protein: 30, carbs: 18, fat: 22, tags: ['bulgogi', 'korean'] },
  { id: 'tteokbokki', name: 'Tteokbokki', serving: '1 bowl', calories: 380, protein: 8, carbs: 72, fat: 7, tags: ['korean'] },
  { id: 'japchae', name: 'Japchae (glass noodles)', serving: '1 plate', calories: 350, protein: 10, carbs: 58, fat: 10, tags: ['noodles', 'korean'] },

  // ── Mexican ──
  { id: 'chicken-quesadilla', name: 'Chicken Quesadilla', serving: '1 whole', calories: 500, protein: 28, carbs: 40, fat: 26, tags: ['quesadilla', 'mexican'] },
  { id: 'nachos-cheese', name: 'Nachos with Cheese', serving: '1 plate', calories: 550, protein: 14, carbs: 52, fat: 32, tags: ['nachos', 'mexican'] },
  { id: 'beef-enchilada', name: 'Beef Enchilada', serving: '2 pieces', calories: 480, protein: 24, carbs: 42, fat: 24, tags: ['enchilada', 'mexican'] },
  { id: 'chicken-fajitas', name: 'Chicken Fajitas', serving: '1 serving', calories: 420, protein: 30, carbs: 34, fat: 18, tags: ['fajita', 'mexican'] },
  { id: 'guacamole', name: 'Guacamole', serving: '1/2 cup', calories: 180, protein: 2, carbs: 10, fat: 16, tags: ['mexican'] },
  { id: 'churros', name: 'Churros', serving: '3 pieces', calories: 290, protein: 4, carbs: 38, fat: 14, tags: ['mexican', 'dessert'] },
  { id: 'beef-taco', name: 'Beef Taco', serving: '1 taco', calories: 210, protein: 12, carbs: 16, fat: 11, tags: ['taco', 'mexican'] },
  { id: 'veg-burrito', name: 'Veg Burrito', serving: '1 burrito', calories: 420, protein: 14, carbs: 62, fat: 13, tags: ['burrito', 'mexican'] },
  { id: 'chicken-burrito', name: 'Chicken Burrito', serving: '1 burrito', calories: 520, protein: 30, carbs: 58, fat: 18, tags: ['burrito', 'mexican'] },

  // ── Middle Eastern ──
  { id: 'chicken-shawarma', name: 'Chicken Shawarma', serving: '1 wrap', calories: 480, protein: 30, carbs: 44, fat: 20, tags: ['shawarma', 'wrap'] },
  { id: 'falafel-wrap', name: 'Falafel Wrap', serving: '1 wrap', calories: 420, protein: 14, carbs: 54, fat: 17, tags: ['falafel', 'wrap'] },
  { id: 'hummus-bowl', name: 'Hummus', serving: '1/2 cup', calories: 200, protein: 8, carbs: 18, fat: 12, tags: ['hummus'] },
  { id: 'chicken-kebab', name: 'Chicken Kebab', serving: '2 skewers', calories: 300, protein: 30, carbs: 6, fat: 17, tags: ['kebab'] },
  { id: 'lamb-kebab', name: 'Lamb Kebab', serving: '2 skewers', calories: 360, protein: 28, carbs: 6, fat: 25, tags: ['kebab'] },
  { id: 'tabbouleh', name: 'Tabbouleh Salad', serving: '1 bowl', calories: 160, protein: 4, carbs: 22, fat: 7, tags: ['salad'] },
  { id: 'baklava', name: 'Baklava', serving: '1 piece', calories: 230, protein: 4, carbs: 28, fat: 12, tags: ['dessert'] },
  { id: 'shakshuka', name: 'Shakshuka', serving: '1 serving', calories: 280, protein: 16, carbs: 18, fat: 17, tags: ['egg'] },
  { id: 'pita-bread', name: 'Pita Bread', serving: '1 piece', calories: 165, protein: 6, carbs: 33, fat: 1, tags: ['bread'] },

  // ── American & Continental ──
  { id: 'hot-dog', name: 'Hot Dog', serving: '1 hot dog', calories: 290, protein: 11, carbs: 24, fat: 17, tags: ['american'] },
  { id: 'mac-and-cheese', name: 'Mac & Cheese', serving: '1 cup', calories: 380, protein: 14, carbs: 44, fat: 17, tags: ['pasta', 'american'] },
  { id: 'waffles', name: 'Waffles', serving: '2 waffles', calories: 310, protein: 8, carbs: 42, fat: 12, tags: ['breakfast', 'american'] },
  { id: 'bacon-strips', name: 'Bacon (cooked)', serving: '3 strips', calories: 160, protein: 12, carbs: 0, fat: 13, tags: ['american'] },
  { id: 'cheeseburger', name: 'Cheeseburger', serving: '1 burger', calories: 500, protein: 25, carbs: 40, fat: 27, tags: ['burger', 'american'] },
  { id: 'buffalo-wings', name: 'Buffalo Wings', serving: '5 wings', calories: 420, protein: 26, carbs: 6, fat: 33, tags: ['american'] },
  { id: 'bbq-ribs', name: 'BBQ Pork Ribs', serving: '1 serving', calories: 550, protein: 34, carbs: 18, fat: 38, tags: ['bbq', 'american'] },
  { id: 'club-sandwich', name: 'Club Sandwich', serving: '1 sandwich', calories: 480, protein: 26, carbs: 42, fat: 22, tags: ['sandwich'] },
  { id: 'philly-cheesesteak', name: 'Philly Cheesesteak', serving: '1 sub', calories: 630, protein: 34, carbs: 48, fat: 33, tags: ['sandwich'] },
  { id: 'croissant', name: 'Butter Croissant', serving: '1 piece', calories: 270, protein: 5, carbs: 26, fat: 16, tags: ['croissant', 'bread'] },
  { id: 'plain-bagel', name: 'Plain Bagel', serving: '1 bagel', calories: 280, protein: 11, carbs: 55, fat: 2, tags: ['bagel', 'bread'] },
  { id: 'quiche', name: 'Quiche Lorraine', serving: '1 slice', calories: 350, protein: 14, carbs: 22, fat: 23, tags: ['quiche', 'egg'] },
  { id: 'paella', name: 'Seafood Paella', serving: '1 plate', calories: 480, protein: 26, carbs: 58, fat: 15, tags: ['paella', 'rice', 'seafood'] },
  { id: 'beef-steak', name: 'Grilled Beef Steak', serving: '150 g', calories: 350, protein: 42, carbs: 0, fat: 20, tags: ['steak', 'beef'] },
  { id: 'roast-chicken', name: 'Roast Chicken', serving: '150 g', calories: 290, protein: 38, carbs: 0, fat: 15, tags: ['chicken'] },
  { id: 'mashed-potatoes', name: 'Mashed Potatoes', serving: '1 cup', calories: 210, protein: 4, carbs: 35, fat: 6, tags: ['potato'] },
  { id: 'pancakes-stack', name: 'Pancakes (stack)', serving: '3 pancakes', calories: 350, protein: 8, carbs: 56, fat: 10, tags: ['breakfast', 'pancakes'] },
  { id: 'pho-bowl', name: 'Pho (beef)', serving: '1 bowl', calories: 420, protein: 30, carbs: 55, fat: 8, tags: ['pho', 'soup', 'noodles'] },
  { id: 'banh-mi', name: 'Banh Mi', serving: '1 sandwich', calories: 400, protein: 20, carbs: 48, fat: 14, tags: ['banh', 'sandwich'] },

  // ── South Indian ──
  { id: 'rava-dosa', name: 'Rava Dosa', serving: '1 piece', calories: 210, protein: 4, carbs: 32, fat: 8, tags: ['dosa', 'indian'] },
  { id: 'ven-pongal', name: 'Ven Pongal', serving: '1 bowl', calories: 280, protein: 8, carbs: 42, fat: 9, tags: ['indian'] },
  { id: 'rasam', name: 'Rasam', serving: '1 bowl', calories: 90, protein: 3, carbs: 14, fat: 3, tags: ['indian', 'soup'] },
  { id: 'coconut-chutney', name: 'Coconut Chutney', serving: '2 tbsp', calories: 80, protein: 1, carbs: 4, fat: 7, tags: ['indian'] },
  { id: 'bisi-bele-bath', name: 'Bisi Bele Bath', serving: '1 bowl', calories: 320, protein: 10, carbs: 50, fat: 9, tags: ['rice', 'indian'] },
  { id: 'mysore-masala-dosa', name: 'Mysore Masala Dosa', serving: '1 piece', calories: 380, protein: 7, carbs: 54, fat: 14, tags: ['dosa', 'indian'] },
  { id: 'filter-coffee', name: 'South Indian Filter Coffee', serving: '1 cup', calories: 90, protein: 2, carbs: 12, fat: 3, tags: ['coffee', 'drink', 'indian'] },

  // ── Bengali ──
  { id: 'macher-jhol', name: 'Macher Jhol (fish curry)', serving: '1 bowl', calories: 240, protein: 22, carbs: 8, fat: 13, tags: ['fish', 'seafood', 'indian'] },
  { id: 'mishti-doi', name: 'Mishti Doi', serving: '1 bowl', calories: 180, protein: 5, carbs: 30, fat: 5, tags: ['indian', 'dessert'] },
  { id: 'rosogolla', name: 'Rosogolla', serving: '2 pieces', calories: 190, protein: 4, carbs: 34, fat: 4, tags: ['indian', 'dessert'] },
  { id: 'sandesh', name: 'Sandesh', serving: '2 pieces', calories: 160, protein: 6, carbs: 22, fat: 6, tags: ['indian', 'dessert'] },
  { id: 'luchi', name: 'Luchi', serving: '2 pieces', calories: 220, protein: 4, carbs: 26, fat: 11, tags: ['indian', 'puri'] },
  { id: 'kosha-mangsho', name: 'Kosha Mangsho (mutton)', serving: '1 bowl', calories: 400, protein: 28, carbs: 10, fat: 28, tags: ['mutton', 'indian'] },

  // ── Punjabi & North ──
  { id: 'sarson-ka-saag', name: 'Sarson Ka Saag', serving: '1 bowl', calories: 220, protein: 8, carbs: 16, fat: 14, tags: ['indian', 'greens'] },
  { id: 'makki-di-roti', name: 'Makki Di Roti', serving: '1 roti', calories: 160, protein: 4, carbs: 28, fat: 4, tags: ['roti', 'indian'] },
  { id: 'chole-bhature', name: 'Chole Bhature', serving: '1 plate', calories: 650, protein: 16, carbs: 80, fat: 30, tags: ['indian'] },
  { id: 'dal-fry', name: 'Dal Fry', serving: '1 bowl', calories: 200, protein: 10, carbs: 24, fat: 7, tags: ['dal', 'indian'] },
  { id: 'kadhi-pakora', name: 'Kadhi Pakora', serving: '1 bowl', calories: 260, protein: 9, carbs: 22, fat: 15, tags: ['indian'] },
  { id: 'shahi-paneer', name: 'Shahi Paneer', serving: '1 bowl', calories: 370, protein: 14, carbs: 16, fat: 28, tags: ['paneer', 'indian'] },
  { id: 'malai-kofta', name: 'Malai Kofta', serving: '1 bowl', calories: 380, protein: 11, carbs: 26, fat: 27, tags: ['indian'] },
  { id: 'kadai-chicken', name: 'Kadai Chicken', serving: '1 bowl', calories: 320, protein: 27, carbs: 10, fat: 19, tags: ['chicken', 'indian'] },
  { id: 'chicken-tikka-masala', name: 'Chicken Tikka Masala', serving: '1 bowl', calories: 420, protein: 30, carbs: 14, fat: 27, tags: ['chicken', 'indian'] },
  { id: 'rogan-josh', name: 'Mutton Rogan Josh', serving: '1 bowl', calories: 400, protein: 28, carbs: 10, fat: 28, tags: ['mutton', 'indian'] },
  { id: 'chicken-korma', name: 'Chicken Korma', serving: '1 bowl', calories: 380, protein: 26, carbs: 12, fat: 26, tags: ['chicken', 'indian'] },
  { id: 'chicken-65', name: 'Chicken 65', serving: '1 plate', calories: 340, protein: 26, carbs: 16, fat: 20, tags: ['chicken', 'indian'] },
  { id: 'seekh-kebab', name: 'Seekh Kebab', serving: '2 pieces', calories: 260, protein: 20, carbs: 6, fat: 18, tags: ['kebab', 'indian'] },
  { id: 'mutton-curry', name: 'Mutton Curry', serving: '1 bowl', calories: 360, protein: 26, carbs: 8, fat: 25, tags: ['mutton', 'indian'] },

  // ── Gujarati / Maharashtrian / Rajasthani ──
  { id: 'khaman-dhokla', name: 'Khaman Dhokla', serving: '3 pieces', calories: 160, protein: 6, carbs: 24, fat: 4, tags: ['dhokla', 'indian'] },
  { id: 'undhiyu', name: 'Undhiyu', serving: '1 bowl', calories: 280, protein: 7, carbs: 30, fat: 15, tags: ['indian', 'veg'] },
  { id: 'fafda', name: 'Fafda', serving: '1 serving', calories: 250, protein: 6, carbs: 24, fat: 14, tags: ['indian', 'snack'] },
  { id: 'khakhra', name: 'Khakhra', serving: '2 pieces', calories: 120, protein: 4, carbs: 20, fat: 3, tags: ['indian', 'snack'] },
  { id: 'misal-pav', name: 'Misal Pav', serving: '1 plate', calories: 380, protein: 14, carbs: 50, fat: 14, tags: ['pav', 'indian'] },
  { id: 'puran-poli', name: 'Puran Poli', serving: '1 piece', calories: 280, protein: 6, carbs: 48, fat: 8, tags: ['indian', 'sweet'] },
  { id: 'sabudana-khichdi', name: 'Sabudana Khichdi', serving: '1 bowl', calories: 300, protein: 5, carbs: 48, fat: 11, tags: ['indian'] },
  { id: 'kanda-poha', name: 'Kanda Poha', serving: '1 plate', calories: 250, protein: 5, carbs: 44, fat: 6, tags: ['poha', 'indian'] },
  { id: 'dal-baati', name: 'Dal Baati Churma', serving: '1 plate', calories: 550, protein: 15, carbs: 70, fat: 24, tags: ['indian'] },
  { id: 'gatte-ki-sabzi', name: 'Gatte Ki Sabzi', serving: '1 bowl', calories: 280, protein: 10, carbs: 24, fat: 16, tags: ['indian', 'sabzi'] },

  // ── Indian breads, sweets & chaat ──
  { id: 'bhatura', name: 'Bhatura', serving: '1 piece', calories: 260, protein: 6, carbs: 36, fat: 10, tags: ['bread', 'indian'] },
  { id: 'tandoori-roti', name: 'Tandoori Roti', serving: '1 piece', calories: 120, protein: 4, carbs: 22, fat: 2, tags: ['roti', 'indian'] },
  { id: 'garlic-naan', name: 'Garlic Naan', serving: '1 piece', calories: 280, protein: 7, carbs: 42, fat: 9, tags: ['naan', 'indian'] },
  { id: 'laccha-paratha', name: 'Laccha Paratha', serving: '1 piece', calories: 250, protein: 5, carbs: 34, fat: 11, tags: ['paratha', 'indian'] },
  { id: 'gajar-halwa', name: 'Gajar Ka Halwa', serving: '1 bowl', calories: 300, protein: 5, carbs: 42, fat: 13, tags: ['indian', 'sweet', 'dessert'] },
  { id: 'rasmalai', name: 'Rasmalai', serving: '2 pieces', calories: 250, protein: 8, carbs: 32, fat: 10, tags: ['indian', 'sweet', 'dessert'] },
  { id: 'kaju-katli', name: 'Kaju Katli', serving: '3 pieces', calories: 200, protein: 4, carbs: 24, fat: 10, tags: ['indian', 'sweet'] },
  { id: 'motichoor-ladoo', name: 'Motichoor Ladoo', serving: '1 piece', calories: 180, protein: 3, carbs: 26, fat: 7, tags: ['indian', 'sweet', 'ladoo'] },
  { id: 'besan-ladoo', name: 'Besan Ladoo', serving: '1 piece', calories: 190, protein: 4, carbs: 22, fat: 10, tags: ['indian', 'sweet', 'ladoo'] },
  { id: 'kulfi', name: 'Kulfi', serving: '1 piece', calories: 200, protein: 5, carbs: 22, fat: 10, tags: ['indian', 'dessert', 'ice cream'] },
  { id: 'rabri', name: 'Rabri', serving: '1 bowl', calories: 280, protein: 8, carbs: 32, fat: 14, tags: ['indian', 'dessert'] },
  { id: 'moong-dal-halwa', name: 'Moong Dal Halwa', serving: '1 bowl', calories: 350, protein: 8, carbs: 40, fat: 18, tags: ['indian', 'sweet', 'dessert'] },
  { id: 'rice-kheer', name: 'Rice Kheer', serving: '1 bowl', calories: 260, protein: 7, carbs: 40, fat: 8, tags: ['indian', 'dessert'] },
  { id: 'soan-papdi', name: 'Soan Papdi', serving: '2 pieces', calories: 170, protein: 2, carbs: 24, fat: 8, tags: ['indian', 'sweet'] },
  { id: 'dahi-puri', name: 'Dahi Puri', serving: '6 pieces', calories: 250, protein: 6, carbs: 36, fat: 9, tags: ['chaat', 'puri', 'indian'] },
  { id: 'papdi-chaat', name: 'Papdi Chaat', serving: '1 plate', calories: 300, protein: 8, carbs: 40, fat: 12, tags: ['chaat', 'indian'] },
  { id: 'aloo-tikki-chaat', name: 'Aloo Tikki Chaat', serving: '1 plate', calories: 320, protein: 7, carbs: 44, fat: 13, tags: ['chaat', 'indian'] },
  { id: 'kachori', name: 'Kachori', serving: '1 piece', calories: 240, protein: 5, carbs: 26, fat: 13, tags: ['indian', 'snack'] },
  { id: 'bread-pakora', name: 'Bread Pakora', serving: '2 pieces', calories: 280, protein: 6, carbs: 32, fat: 15, tags: ['pakora', 'indian', 'snack'] },
  { id: 'veg-momos', name: 'Veg Momos', serving: '5 pieces', calories: 220, protein: 6, carbs: 38, fat: 5, tags: ['momos', 'dumpling', 'indian'] },
  { id: 'chicken-momos', name: 'Chicken Momos', serving: '5 pieces', calories: 260, protein: 14, carbs: 34, fat: 7, tags: ['momos', 'dumpling', 'indian'] },

  // ── Vegetables ──
  { id: 'spinach-cooked', name: 'Spinach (cooked)', serving: '1 cup', calories: 41, protein: 5, carbs: 7, fat: 0.5, tags: ['veg', 'greens'] },
  { id: 'cauliflower', name: 'Cauliflower (cooked)', serving: '1 cup', calories: 50, protein: 4, carbs: 10, fat: 0.5, tags: ['veg'] },
  { id: 'carrot-raw', name: 'Carrot (raw)', serving: '1 medium', calories: 25, protein: 0.6, carbs: 6, fat: 0.1, tags: ['veg'] },
  { id: 'cabbage', name: 'Cabbage (raw)', serving: '1 cup', calories: 22, protein: 1, carbs: 5, fat: 0.1, tags: ['veg'] },
  { id: 'bell-pepper', name: 'Bell Pepper', serving: '1 medium', calories: 30, protein: 1, carbs: 7, fat: 0.3, tags: ['veg', 'pepper'] },
  { id: 'mushroom', name: 'Mushrooms (cooked)', serving: '1 cup', calories: 44, protein: 3, carbs: 8, fat: 0.7, tags: ['veg', 'mushroom'] },
  { id: 'corn-boiled', name: 'Sweet Corn (boiled)', serving: '1 cup', calories: 130, protein: 5, carbs: 29, fat: 2, tags: ['veg', 'corn'] },
  { id: 'green-peas', name: 'Green Peas', serving: '1 cup', calories: 118, protein: 8, carbs: 21, fat: 0.6, tags: ['veg', 'peas'] },
  { id: 'okra-bhindi', name: 'Bhindi / Okra (cooked)', serving: '1 cup', calories: 90, protein: 3, carbs: 12, fat: 4, tags: ['veg', 'bhindi', 'sabzi'] },
  { id: 'aloo-gobi', name: 'Aloo Gobi', serving: '1 bowl', calories: 200, protein: 5, carbs: 26, fat: 9, tags: ['veg', 'indian', 'sabzi', 'potato'] },
  { id: 'mixed-veg-salad', name: 'Mixed Veg Salad', serving: '1 bowl', calories: 90, protein: 3, carbs: 14, fat: 3, tags: ['veg', 'salad'] },
  { id: 'coleslaw', name: 'Coleslaw', serving: '1/2 cup', calories: 150, protein: 1, carbs: 12, fat: 11, tags: ['veg', 'salad'] },
  { id: 'cucumber', name: 'Cucumber', serving: '1 cup', calories: 16, protein: 0.7, carbs: 4, fat: 0.1, tags: ['veg'] },
  { id: 'beetroot', name: 'Beetroot (boiled)', serving: '1 cup', calories: 60, protein: 2, carbs: 13, fat: 0.2, tags: ['veg'] },

  // ── Fruits ──
  { id: 'pineapple', name: 'Pineapple', serving: '1 cup', calories: 82, protein: 1, carbs: 22, fat: 0.2, tags: ['fruit'] },
  { id: 'cherries', name: 'Cherries', serving: '1 cup', calories: 87, protein: 1.5, carbs: 22, fat: 0.3, tags: ['fruit'] },
  { id: 'peach', name: 'Peach', serving: '1 medium', calories: 58, protein: 1.4, carbs: 14, fat: 0.4, tags: ['fruit'] },
  { id: 'plum', name: 'Plum', serving: '1 medium', calories: 30, protein: 0.5, carbs: 8, fat: 0.2, tags: ['fruit'] },
  { id: 'lychee', name: 'Lychee', serving: '10 pieces', calories: 66, protein: 0.8, carbs: 17, fat: 0.4, tags: ['fruit'] },
  { id: 'avocado-fruit', name: 'Avocado', serving: '1/2 fruit', calories: 160, protein: 2, carbs: 9, fat: 15, tags: ['fruit'] },
  { id: 'muskmelon', name: 'Muskmelon', serving: '1 cup', calories: 54, protein: 1.3, carbs: 13, fat: 0.3, tags: ['fruit'] },
  { id: 'chikoo-sapota', name: 'Chikoo / Sapota', serving: '1 medium', calories: 83, protein: 0.5, carbs: 20, fat: 1.1, tags: ['fruit'] },
  { id: 'custard-apple', name: 'Custard Apple', serving: '1 medium', calories: 100, protein: 2, carbs: 25, fat: 0.5, tags: ['fruit'] },
  { id: 'raspberries', name: 'Raspberries', serving: '1 cup', calories: 64, protein: 1.5, carbs: 15, fat: 0.8, tags: ['fruit'] },

  // ── Grains, dairy & nuts ──
  { id: 'couscous', name: 'Couscous (cooked)', serving: '1 cup', calories: 176, protein: 6, carbs: 36, fat: 0.3, tags: ['couscous', 'grain'] },
  { id: 'whole-wheat-pasta', name: 'Whole Wheat Pasta', serving: '1 cup', calories: 180, protein: 8, carbs: 37, fat: 1.5, tags: ['pasta', 'grain'] },
  { id: 'white-bread-slice', name: 'White Bread', serving: '1 slice', calories: 80, protein: 3, carbs: 15, fat: 1, tags: ['bread'] },
  { id: 'brown-bread-slice', name: 'Brown Bread', serving: '1 slice', calories: 75, protein: 4, carbs: 13, fat: 1, tags: ['bread'] },
  { id: 'tortilla-wrap', name: 'Tortilla Wrap', serving: '1 medium', calories: 140, protein: 4, carbs: 24, fat: 3.5, tags: ['wrap', 'bread'] },
  { id: 'whole-milk', name: 'Whole Milk', serving: '1 cup', calories: 150, protein: 8, carbs: 12, fat: 8, tags: ['dairy', 'drink'] },
  { id: 'skim-milk', name: 'Skim Milk', serving: '1 cup', calories: 83, protein: 8, carbs: 12, fat: 0.2, tags: ['dairy', 'drink'] },
  { id: 'cheddar-cheese', name: 'Cheddar Cheese', serving: '30 g', calories: 120, protein: 7, carbs: 0.4, fat: 10, tags: ['dairy', 'cheese'] },
  { id: 'mozzarella', name: 'Mozzarella', serving: '30 g', calories: 85, protein: 6, carbs: 1, fat: 6, tags: ['dairy', 'cheese'] },
  { id: 'feta-cheese', name: 'Feta Cheese', serving: '30 g', calories: 80, protein: 4, carbs: 1, fat: 6, tags: ['dairy', 'cheese'] },
  { id: 'vanilla-ice-cream', name: 'Vanilla Ice Cream', serving: '1 scoop', calories: 140, protein: 2, carbs: 16, fat: 7, tags: ['dessert', 'ice cream'] },
  { id: 'peanuts', name: 'Peanuts', serving: '30 g', calories: 170, protein: 7, carbs: 5, fat: 14, tags: ['nuts'] },
  { id: 'pistachios', name: 'Pistachios', serving: '30 g', calories: 159, protein: 6, carbs: 8, fat: 13, tags: ['nuts'] },
  { id: 'chia-seeds', name: 'Chia Seeds', serving: '2 tbsp', calories: 138, protein: 5, carbs: 12, fat: 9, tags: ['seeds'] },
  { id: 'flax-seeds', name: 'Flax Seeds', serving: '2 tbsp', calories: 110, protein: 4, carbs: 6, fat: 8, tags: ['seeds'] },
  { id: 'mixed-nuts', name: 'Mixed Nuts', serving: '30 g', calories: 173, protein: 5, carbs: 6, fat: 15, tags: ['nuts'] },

  // ── More brands ──
  { id: 'chipotle-bowl', name: 'Chipotle Burrito Bowl', serving: '1 bowl', calories: 700, protein: 40, carbs: 65, fat: 30, tags: ['brand', 'chipotle'] },
  { id: 'wendys-baconator', name: "Wendy's Baconator", serving: '1 burger', calories: 950, protein: 56, carbs: 40, fat: 62, tags: ['brand', 'wendys'] },
  { id: 'popeyes-chicken', name: 'Popeyes Fried Chicken', serving: '1 piece', calories: 320, protein: 21, carbs: 12, fat: 21, tags: ['brand', 'popeyes'] },
  { id: 'chickfila-sandwich', name: 'Chick-fil-A Chicken Sandwich', serving: '1 sandwich', calories: 440, protein: 28, carbs: 40, fat: 19, tags: ['brand', 'chick-fil-a'] },
  { id: 'nandos-peri-chicken', name: "Nando's Peri-Peri Chicken (1/4)", serving: '1/4 chicken', calories: 300, protein: 38, carbs: 2, fat: 16, tags: ['brand', 'nandos'] },
  { id: 'ccd-cappuccino', name: 'Cafe Coffee Day Cappuccino', serving: '1 regular', calories: 160, protein: 6, carbs: 20, fat: 6, tags: ['brand', 'ccd', 'coffee'] },
  { id: 'wow-momo', name: 'Wow! Momo (steamed, 5)', serving: '5 pieces', calories: 240, protein: 8, carbs: 40, fat: 6, tags: ['brand', 'momos'] },
  { id: 'doritos', name: 'Doritos', serving: '30 g', calories: 150, protein: 2, carbs: 18, fat: 8, tags: ['brand', 'chips'] },
  { id: 'pringles', name: 'Pringles', serving: '15 crisps', calories: 150, protein: 1, carbs: 15, fat: 9, tags: ['brand', 'chips'] },
  { id: 'cornetto', name: 'Cornetto Cone', serving: '1 cone', calories: 200, protein: 3, carbs: 24, fat: 10, tags: ['brand', 'ice cream'] },
  { id: 'magnum-bar', name: 'Magnum Ice Cream Bar', serving: '1 bar', calories: 260, protein: 3, carbs: 24, fat: 17, tags: ['brand', 'ice cream'] },
  { id: 'nestle-munch', name: 'Nestle Munch', serving: '1 bar', calories: 120, protein: 1, carbs: 15, fat: 6, tags: ['brand', 'nestle'] },
  { id: 'five-star', name: 'Cadbury 5 Star', serving: '1 bar', calories: 200, protein: 2, carbs: 30, fat: 8, tags: ['brand', 'cadbury'] },
  { id: 'dairy-milk-silk', name: 'Cadbury Dairy Milk Silk', serving: '1 bar', calories: 320, protein: 4, carbs: 36, fat: 18, tags: ['brand', 'cadbury'] },
  { id: 'ferrero-rocher', name: 'Ferrero Rocher', serving: '3 pieces', calories: 220, protein: 3, carbs: 17, fat: 16, tags: ['brand', 'chocolate'] },
  { id: 'kinder-joy', name: 'Kinder Joy', serving: '1 piece', calories: 120, protein: 2, carbs: 12, fat: 7, tags: ['brand', 'chocolate'] },
  { id: 'mms', name: "M&M's", serving: '1 pack', calories: 240, protein: 2, carbs: 34, fat: 10, tags: ['brand', 'chocolate'] },
  { id: 'twix', name: 'Twix', serving: '1 pack', calories: 250, protein: 2, carbs: 34, fat: 12, tags: ['brand', 'chocolate'] },
  { id: 'quaker-oats-brand', name: 'Quaker Oats (dry)', serving: '40 g', calories: 150, protein: 5, carbs: 27, fat: 3, tags: ['brand', 'oats', 'breakfast'] },
  { id: 'horlicks', name: 'Horlicks (with milk)', serving: '1 glass', calories: 180, protein: 8, carbs: 27, fat: 4, tags: ['brand'] },
  { id: 'nature-valley-bar', name: 'Nature Valley Granola Bar', serving: '2 bars', calories: 190, protein: 4, carbs: 29, fat: 7, tags: ['brand', 'bar'] },
  { id: 'yoga-bar', name: 'Yoga Bar Protein Bar', serving: '1 bar', calories: 210, protein: 20, carbs: 22, fat: 6, tags: ['brand', 'protein', 'bar'] },
  { id: 'fanta', name: 'Fanta', serving: '330 ml can', calories: 160, protein: 0, carbs: 44, fat: 0, tags: ['brand', 'drink'] },
  { id: 'mountain-dew', name: 'Mountain Dew', serving: '330 ml can', calories: 170, protein: 0, carbs: 46, fat: 0, tags: ['brand', 'drink'] },
  { id: 'thums-up', name: 'Thums Up', serving: '330 ml can', calories: 155, protein: 0, carbs: 42, fat: 0, tags: ['brand', 'cola', 'drink'] },
  { id: 'sprite-limca', name: 'Limca', serving: '330 ml can', calories: 140, protein: 0, carbs: 38, fat: 0, tags: ['brand', 'drink'] },
  { id: 'maaza', name: 'Maaza Mango Drink', serving: '250 ml', calories: 150, protein: 0, carbs: 37, fat: 0, tags: ['brand', 'juice', 'drink'] },
  { id: 'frooti', name: 'Frooti', serving: '200 ml', calories: 110, protein: 0, carbs: 27, fat: 0, tags: ['brand', 'juice', 'drink'] },
  { id: 'real-juice', name: 'Real Fruit Juice', serving: '200 ml', calories: 120, protein: 0, carbs: 29, fat: 0, tags: ['brand', 'juice', 'drink'] },
  { id: 'tropicana', name: 'Tropicana Orange Juice', serving: '250 ml', calories: 110, protein: 2, carbs: 26, fat: 0, tags: ['brand', 'juice', 'drink'] },
  { id: 'sting-energy', name: 'Sting Energy Drink', serving: '250 ml', calories: 120, protein: 0, carbs: 30, fat: 0, tags: ['brand', 'drink'] },
  { id: 'bru-coffee', name: 'Bru Instant Coffee (with milk)', serving: '1 cup', calories: 90, protein: 3, carbs: 12, fat: 3, tags: ['brand', 'coffee', 'drink'] },
  { id: 'rooh-afza', name: 'Rooh Afza (with milk)', serving: '1 glass', calories: 150, protein: 4, carbs: 30, fat: 3, tags: ['brand', 'drink'] },
  { id: 'ensure-shake', name: 'Ensure Nutrition Shake', serving: '1 glass', calories: 220, protein: 9, carbs: 33, fat: 6, tags: ['brand', 'protein', 'drink'] },
  { id: 'muscleblaze-whey', name: 'MuscleBlaze Whey Protein', serving: '1 scoop', calories: 120, protein: 25, carbs: 3, fat: 1.5, tags: ['brand', 'protein', 'whey'] },
];

const QUICK_FOOD_IDS = [
  'roti', 'rice-cooked', 'dal-tadka', 'curd', 'banana', 'egg-boiled',
  'chicken-breast', 'paneer-raw', 'oats', 'poha', 'idli', 'chai',
  'apple', 'whey', 'sprouts', 'coffee-black',
];

const GROUP_TERMS: Record<Exclude<FoodGroupId, 'quick'>, string[]> = {
  indian: ['roti', 'paratha', 'rice', 'dal', 'paneer', 'sabzi', 'biryani', 'dosa', 'idli', 'poha', 'upma', 'khichdi', 'thali', 'chaat', 'puri', 'pav', 'vada', 'lassi', 'chai', 'kheer', 'kulcha', 'appam', 'puttu', 'chilla', 'dhokla', 'thepla'],
  protein: ['chicken', 'egg', 'fish', 'mutton', 'paneer', 'tofu', 'soya', 'whey', 'sprouts', 'yogurt', 'salmon', 'tuna', 'shrimp', 'beef', 'lentils', 'chickpeas', 'beans', 'tempeh', 'protein'],
  seafood: ['seafood', 'fish', 'salmon', 'tuna', 'shrimp', 'prawn', 'crab', 'lobster', 'squid', 'calamari', 'oyster', 'mussel', 'clam', 'scallop', 'cod', 'tilapia', 'mackerel', 'sardine', 'pomfret', 'anchovy', 'basa', 'rohu', 'hilsa', 'surmai', 'trout', 'haddock', 'snapper'],
  breakfast: ['oats', 'muesli', 'cornflakes', 'bread', 'egg', 'omelette', 'poha', 'upma', 'idli', 'dosa', 'uttapam', 'chilla', 'dhokla', 'thepla', 'yogurt', 'smoothie', 'pancakes', 'toast'],
  snacks: ['samosa', 'pakora', 'makhana', 'biscuits', 'chips', 'chocolate', 'bhel', 'puri', 'vada', 'roll', 'dabeli', 'khandvi', 'trail', 'popcorn', 'bar', 'fries', 'momos', 'ice cream', 'rasgulla', 'jalebi', 'jamun'],
  brands: ['brand'],
  drinks: ['chai', 'coffee', 'juice', 'cola', 'water', 'lassi', 'buttermilk', 'chaas', 'tea', 'drink', 'smoothie', 'beer'],
  fruit: ['banana', 'apple', 'mango', 'orange', 'grapes', 'papaya', 'pomegranate', 'watermelon', 'strawberries', 'blueberries', 'kiwi', 'pear', 'guava', 'dates'],
  global: ['pasta', 'pizza', 'burger', 'sandwich', 'rice', 'noodles', 'fries', 'salad', 'wrap', 'burrito', 'sushi', 'ramen', 'pho', 'taco', 'falafel', 'hummus', 'soup', 'toast', 'spaghetti', 'lasagna', 'risotto', 'gnocchi', 'ravioli', 'carbonara', 'alfredo', 'penne', 'udon', 'tempura', 'teriyaki', 'gyoza', 'katsu', 'bibimbap', 'bulgogi', 'kimchi', 'pad thai', 'satay', 'quesadilla', 'nachos', 'enchilada', 'fajita', 'shawarma', 'kebab', 'gyro', 'paella', 'croissant', 'bagel', 'crepe', 'quiche', 'steak', 'bbq', 'dumpling', 'manchurian', 'chow', 'hakka', 'schnitzel', 'meatball', 'stir fry', 'banh', 'moussaka', 'couscous', 'quinoa'],
  veg: ['broccoli', 'spinach', 'cauliflower', 'carrot', 'cabbage', 'pepper', 'mushroom', 'zucchini', 'potato', 'corn', 'peas', 'beans', 'bhindi', 'okra', 'eggplant', 'brinjal', 'tomato', 'cucumber', 'lettuce', 'kale', 'asparagus', 'beetroot', 'pumpkin', 'gourd', 'salad', 'veg', 'greens', 'sprout'],
};

function searchableText(food: FoodItem): string {
  return [food.name, food.serving, ...(food.tags ?? [])].join(' ').toLowerCase();
}

export function foodsForGroup(group: FoodGroupId, limit = 12): FoodItem[] {
  if (group === 'quick') {
    const byId = new Map(FOOD_DB.map(food => [food.id, food]));
    return QUICK_FOOD_IDS.map(id => byId.get(id)).filter(Boolean).slice(0, limit) as FoodItem[];
  }
  const terms = GROUP_TERMS[group];
  return FOOD_DB.filter(food => {
    const haystack = searchableText(food);
    return terms.some(term => haystack.includes(term));
  }).slice(0, limit);
}

/** Substring search over names, servings, and tags; empty query returns nothing. */
export function searchFoods(query: string, limit = 12): FoodItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const starts: FoodItem[] = [];
  const contains: FoodItem[] = [];
  for (const f of FOOD_DB) {
    const name = f.name.toLowerCase();
    const haystack = searchableText(f);
    if (name.startsWith(q)) starts.push(f);
    else if (haystack.includes(q)) contains.push(f);
  }
  return [...starts, ...contains].slice(0, limit);
}
