INSERT INTO public.daily_question_bank (question, sort_order) VALUES
  ('Why do we park in driveways and drive on parkways?', 71),
  ('Success is just failure that hasn''t happened yet.', 72),
  ('If nothing is impossible, is it possible for something to be impossible?', 73),
  ('Sleep is just a free trial of death with ads made of weird dreams.', 74),
  ('Your future self is watching you right now through memories.', 75),
  ('The brain named itself and then spent centuries trying to understand itself.', 76),
  ('Clocks don''t tell time; they just count how many times a gear spins while we assign meaning to it.', 77),
  ('Lasers are just light that went to private school.', 78),
  ('We buy garbage bags just to throw them away.', 79),
  ('Every book you''ve ever read is just 26 letters arranged in different combinations.', 80),
  ('An unread email is a Schrödinger''s crisis: simultaneously urgent and irrelevant until opened.', 81),
  ('If tomatoes are a fruit, then ketchup is technically a smoothie.', 82),
  ('Water isn''t wet by itself; it just makes everything else wet.', 83),
  ('Wi-Fi is invisible electricity that turns impatience into a personality trait.', 84),
  ('The word ''queue'' is just the letter Q followed by four silent letters waiting in line.', 85),
  ('Mirrors don''t create images; they just reflect reality with an existential delay of light.', 86),
  ('You''ve never seen your own face with your own eyes, only reflections and photos.', 87),
  ('Coffee doesn''t give you energy; it borrows tomorrow''s energy at an unreasonable interest rate.', 88),
  ('An alarm clock is the only device you buy with the sole intention of wanting to destroy it daily.', 89),
  ('We clean our houses before guests arrive to convince them we don''t live the way we actually live.', 90),
  ('Walking into another room and forgetting why is your brain hitting the reload button without cache.', 91),
  ('Fire trucks are actually water trucks.', 92),
  ('Swimming pools are just giant bathtubs where we all agree to swim in each other''s bathwater.', 93),
  ('Keyboards are pianos where each key plays a thought instead of a chord.', 94),
  ('We put round pizzas in square boxes and eat them in triangles.', 95),
  ('History is just gossip with footnotes and a museum budget.', 96),
  ('When you clean a vacuum cleaner, you become the vacuum cleaner.', 97),
  ('Elevators are just vertical rooms that move while you pretend not to make eye contact.', 98),
  ('You never realize how long a minute is until you microwave something.', 99),
  ('The universe is under no obligation to make sense to you, but it sure likes watching you try.', 100),
  ('If you think nobody cares if you''re alive, try missing a couple of car payments.', 101),
  ('I followed my heart and it led me directly to the refrigerator.', 102),
  ('Common sense is like deodorant: the people who need it most never use it.', 103),
  ('My wallet is like an onion: opening it makes me cry.', 104),
  ('Teamwork is essential; it allows you to blame someone else when things go wrong.', 105),
  ('I''m not procrastinating; I''m giving my ideas time to marinate in panic.', 106),
  ('Behind every successful person is a substantial amount of coffee and a deep fear of inadequacy.', 107),
  ('''Per my last email'' is the professional equivalent of ''Can you even read?''', 108),
  ('I put the ''pro'' in procrastination and the ''con'' in consequences.', 109),
  ('Experience is what you get right after you needed it.', 110),
  ('The early bird might get the worm, but the second mouse gets the cheese.', 111),
  ('A meeting is an event where minutes are kept and hours are wasted.', 112),
  ('I have a degree in overthinking with a minor in catastrophizing.', 113),
  ('Nothing boosts productivity like the terror of a deadline 30 minutes away.', 114),
  ('If stress burned calories, I''d be a supermodel by now.', 115),
  ('Hard work pays off in the future; laziness pays off right now.', 116),
  ('I''m not arguing; I''m just explaining loudly why you''re wrong.', 117),
  ('My budget is based on the hopeful assumption that nothing unexpected ever happens in life.', 118),
  ('Adulting is just saying ''We have food at home'' until you eventually order takeout anyway.', 119),
  ('If at first you don''t succeed, skydiving is definitely not for you.', 120),
  ('I love deadlines. I love the whooshing noise they make as they go by.', 121),
  ('My sleep schedule is a game of Jenga played by a toddler.', 122),
  ('Nothing unites an office quite like a shared hatred of the temperature setting.', 123),
  ('I have multiple browser tabs open in my brain, and music is playing from an unknown one.', 124),
  ('The road to success is always under construction and detour signs are written in fine print.', 125),
  ('Exercise is the answer, but what was the question that made me want to suffer?', 126),
  ('Every email thread with more than four people is a slow-motion car crash in text format.', 127),
  ('I''m one minor inconvenience away from starting a completely new life in a secluded forest.', 128),
  ('''Let''s take this offline'' means ''I want to disagree with you without witnesses.''', 129),
  ('Being an adult is mostly staring at your phone while feeling guilty about things you should be doing.', 130),
  ('The version of you that exists in other people''s minds is entirely out of your control.', 131),
  ('We don''t see things as they are; we see things as we are.', 132),
  ('The cure for boredom is curiosity, but there is no cure for curiosity.', 133),
  ('You are not a drop in the ocean; you are the entire ocean in a single drop.', 134),
  ('The price of anything is the amount of life you exchange for it.', 135),
  ('Silence is not empty; it is full of answers you are too loud to hear.', 136),
  ('Nostalgia is a file folder where memory files away the pain and keeps only the warm lighting.', 137),
  ('We are all stories in the end; make sure yours is worth telling around a campfire.', 138),
  ('The privilege of a lifetime is to become who you truly are.', 139),
  ('We suffer more often in imagination than in reality.', 140),
  ('The meaning of life is not something you discover; it is something you construct.', 141),
  ('You are what you do when no one is watching and nothing is on the line.', 142),
  ('Sometimes the hardest part isn''t letting go, but learning to start over without the weight.', 143),
  ('Grief is love with nowhere to go.', 144),
  ('We cross our bridges when we come to them and burn them behind us, with nothing to show for our progress but a memory of smoke.', 145),
  ('The man who moves a mountain begins by carrying away small stones.', 146),
  ('Almost everything will work again if you unplug it for a few minutes, including you.', 147),
  ('People will forget what you said, but they will never forget how you made them feel.', 148),
  ('To understand everything is to forgive everything.', 149),
  ('The past is a place of reference, not a place of residence.', 150),
  ('You can be the ripest, juiciest peach in the world, and there will still be someone who hates peaches.', 151),
  ('A ship in harbor is safe, but that is not what ships are built for.', 152),
  ('Time expands when you pay attention to it and vanishes when you try to hold it.', 153),
  ('The bird does not trust the branch; it trusts its own wings.', 154),
  ('What you seek is seeking you, waiting for you to become quiet enough to meet it.', 155),
  ('It is not that we have a short time to live, but that we waste a lot of it.', 156),
  ('Character is revealed when the outcome doesn''t favor you.', 157),
  ('The quieter you become, the more you are able to hear.', 158),
  ('You cannot step into the same river twice, for it is not the same river and you are not the same person.', 159),
  ('Wisdom begins when you realize how much of your certainty was just borrowed confidence.', 160),
  ('Start where you are, use what you have, do what you can.', 161),
  ('The master has failed more times than the beginner has even tried.', 162),
  ('Small daily improvements over time lead to stunning results.', 163),
  ('You don''t have to be great to start, but you have to start to be great.', 164),
  ('Discipline is choosing between what you want now and what you want most.', 165),
  ('Don''t count the days; make the days count.', 166),
  ('Action is the foundational key to all success.', 167),
  ('Your potential is an uncashed check waiting for your courage to sign it.', 168),
  ('Comfort is the enemy of progress.', 169),
  ('Fall seven times, stand up eight.', 170),
  ('The best time to plant a tree was 20 years ago; the second best time is now.', 171),
  ('It always seems impossible until it''s done.', 172),
  ('Don''t downgrade your dreams just to fit your current reality; upgrade your conviction.', 173),
  ('Success is the sum of small efforts repeated day in and day out.', 174),
  ('Motivation gets you going, but habit is what keeps you growing.', 175),
  ('The secret of getting ahead is getting started.', 176),
  ('If you want something you''ve never had, you must be willing to do something you''ve never done.', 177),
  ('Do something today that your future self will thank you for.', 178),
  ('Difficult roads often lead to beautiful destinations.', 179),
  ('Energy flows where attention goes.', 180),
  ('You don''t find willpower; you create it.', 181),
  ('A river cuts through rock not because of its power, but because of its persistence.', 182),
  ('Be so good they can''t ignore you.', 183),
  ('Great things never came from comfort zones.', 184),
  ('The only limit to our realization of tomorrow will be our doubts of today.', 185),
  ('If you get tired, learn to rest, not to quit.', 186),
  ('Opportunities don''t happen; you create them.', 187),
  ('The harder you work for something, the greater you''ll feel when you achieve it.', 188),
  ('Don''t watch the clock; do what it does: keep going.', 189),
  ('Success doesn''t just find you; you have to go out and get it.', 190),
  ('Less is more, until it isn''t.', 191),
  ('Clarity comes from action, not thought.', 192),
  ('What you resist persists.', 193),
  ('Done is better than perfect.', 194),
  ('Urgency is loud; importance is quiet.', 195),
  ('Listening is not waiting for your turn to speak.', 196),
  ('If you speak the truth, have one foot in the stirrup.', 197),
  ('The obstacle is the way.', 198),
  ('A smooth sea never made a skilled sailor.', 199),
  ('Comparison is the thief of joy.', 200),
  ('Simplicity is the ultimate sophistication.', 201),
  ('Know yourself and know your worth.', 202),
  ('You teach people how to treat you by what you tolerate.', 203),
  ('Be curious, not judgmental.', 204),
  ('Still waters run deep.', 205),
  ('Speak only if it improves upon silence.', 206),
  ('What you allow is what will continue.', 207),
  ('Not all storms come to disrupt your life; some come to clear your path.', 208),
  ('A busy calendar is often an excuse for an empty mind.', 209),
  ('Beware of the barrenness of a busy life.', 210),
  ('Heavy hearts are easiest lifted by helping hands.', 211),
  ('Kindness costs nothing but buys everything.', 212),
  ('An open mind without a filter is just an open garbage can.', 213),
  ('Half the harm in the world is done by people who want to feel important.', 214),
  ('What gets measured gets managed.', 215),
  ('You can''t pour from an empty cup.', 216),
  ('Don''t set yourself on fire to keep others warm.', 217),
  ('The best revenge is massive success and total peace of mind.', 218),
  ('If you chase two rabbits, you catch neither.', 219),
  ('Trust takes years to build, seconds to break, and forever to repair.', 220),
  ('Your shadow is proof that light traveled 93 million miles just to be blocked by you.', 221),
  ('Autocorrect has become my worst enema.', 222),
  ('Why is ''abbreviation'' such a long word?', 223),
  ('A bookmark is just a piece of paper that says ''I quit reading here, but I swear I will come back.''', 224),
  ('The oldest photograph of a human was taken accidentally because he stood still getting his shoes shined.', 225),
  ('We spend the first two years teaching kids to walk and talk, and the next sixteen telling them to sit down and be quiet.', 226),
  ('Nothing makes you question your motor skills quite like trying to put on a fitted sheet.', 227),
  ('Teeth are the only bones we clean with minty paste in front of a mirror twice a day.', 228),
  ('A bank is a place that will lend you an umbrella when the sun is shining and ask for it back when it rains.', 229),
  ('If you replace every part of a ship over time, is it still the same ship? If you replace every thought, are you still you?', 230),
  ('When you say ''forward'' or ''back'', your lips move in those directions.', 231),
  ('We spend one-third of our lives unconscious and call it necessary maintenance.', 232),
  ('An eraser is an admission of human fallibility wrapped in pink rubber.', 233),
  ('Sunglasses are just tiny dark windows you wear to hide your judgment.', 234),
  ('Every used car you pass is someone else''s resolved headache or future disaster.', 235),
  ('If a mosquito can ruin your sleep, never underestimate the power of being small and annoying.', 236),
  ('We lock doors not to keep the world out, but to give ourselves permission to let our guard down.', 237),
  ('A playlist is an emotional time machine that operates in four-minute increments.', 238),
  ('The horizon moves with you because the end of the world is always a matter of perspective.', 239),
  ('Your tongue is currently resting against the roof of your mouth, and now you can''t un-feel it.', 240),
  ('We pay monthly subscriptions for entertainment to distract us from the jobs we work to pay for subscriptions.', 241),
  ('If practice makes perfect, but nobody''s perfect, then why practice?', 242),
  ('The alphabet doesn''t need to be in that order; we just accepted someone''s arbitrary song.', 243),
  ('You can''t hum while holding your nose, and 90% of people test this immediately.', 244),
  ('An apology without change is just manipulation wearing a Sunday suit.', 245),
  ('We live on a blue marble spinning at 1,000 miles per hour, yet we stress over a typo in an email.', 246),
  ('The snooze button is a device that lets you experience waking up exhausted multiple times in one morning.', 247),
  ('A refrigerator light is the only witness to your midnight existential crises.', 248),
  ('Coins in a fountain are wishes paid for in loose copper that nobody needed anyway.', 249),
  ('If you try to fail and succeed, which one did you actually do?', 250),
  ('You don''t need a parachute to go skydiving; you only need a parachute to go skydiving twice.', 251),
  ('I''m not indecisive; I just like to thoroughly explore every terrible option first.', 252),
  ('The problem with common sense is that it isn''t very common.', 253),
  ('Nothing says ''I value your input'' quite like nodding while thinking about lunch.', 254),
  ('My daily routine consists of wishing for the weekend from Monday morning until Friday night.', 255),
  ('Patience is what you have when there are too many witnesses around.', 256),
  ('Some people bring joy wherever they go; others bring joy whenever they go.', 257),
  ('My favorite workout is a cross between a lunge and a crunch: I call it lunch.', 258),
  ('A clean desk is a sign of a cluttered desk drawer.', 259),
  ('I told my suitcase there would be no vacation this year; now I''m dealing with emotional baggage.', 260),
  ('If you''re going to tell people the truth, make them laugh, otherwise they''ll kill you.', 261),
  ('I finally got 8 hours of sleep; it took me four days, but I got them.', 262),
  ('''Quick sync'' is corporate speak for ''I could have typed this in one sentence, but I prefer your pain.''', 263),
  ('Money can''t buy happiness, but it can buy a jet ski, and nobody is sad on a jet ski.', 264),
  ('My superpower is remembering an embarrassing thing I did in middle school right before falling asleep.', 265),
  ('A clear conscience is usually the result of a bad memory.', 266),
  ('Life is short; smile while you still have all your teeth.', 267),
  ('I''m on a seafood diet: I see food, and I eat it.', 268),
  ('Don''t worry about what people think of you; they''re too busy worrying about what you think of them.', 269),
  ('The first five days after the weekend are always the hardest.', 270),
  ('I refuse to join any club that would have someone like me as a member.', 271),
  ('The easiest way to find something lost is to buy a replacement.', 272),
  ('We spend the weekend recovering from the week and the week dreading the next.', 273),
  ('''No offense'' is always followed immediately by the most offensive statement imaginable.', 274),
  ('I''m not lazy; I''m on energy-saving mode to reduce my carbon footprint.', 275),
  ('If two wrongs don''t make a right, try three.', 276),
  ('My goal for today is to be as productive as my phone''s battery drain.', 277),
  ('A diploma is just a receipt for an education you mostly have to relearn on the job.', 278),
  ('I''m great at multitasking: I can waste time, be unproductive, and procrastinate all at once.', 279),
  ('Smile today; tomorrow could be worse.', 280),
  ('Every sunset is proof that endings can be beautiful too.', 281),
  ('You don''t have to attend every argument you''re invited to.', 282),
  ('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 283),
  ('If you want to know what someone truly values, look at their calendar and their bank statement.', 284),
  ('Forgiveness is giving up the hope that the past could be any different.', 285),
  ('The wound is the place where the light enters you.', 286),
  ('Solitude is where you find what you lost in the crowd.', 287),
  ('We measure time in seconds, but we experience it in heartbeats.', 288),
  ('The cave you fear to enter holds the treasure you seek.', 289),
  ('Peace does not mean to be in a place where there is no noise; it means to be in the midst of those things and still be calm in your heart.', 290),
  ('A tree with strong roots laughs at storms that break rigid towers.', 291),
  ('We never remember days; we remember moments.', 292),
  ('The deepest rivers always flow with the least sound.', 293),
  ('To love someone is to learn the song in their heart and sing it back to them when they have forgotten.', 294),
  ('The only thing you take with you when you leave is what you left behind in others.', 295),
  ('A secret to happiness is accepting that you cannot control the waves, only how you ride them.', 296),
  ('Your life does not get better by chance; it gets better by change.', 297),
  ('The ego wants comfort; the soul wants growth.', 298),
  ('We are shaped by our thoughts; we become what we think.', 299),
  ('What is meant for you will not pass you by, but it won''t knock down your door either.', 300),
  ('In the depth of winter, I finally learned that within me there lay an invincible summer.', 301),
  ('The truth does not mind being questioned; a lie does not tolerate being challenged.', 302),
  ('You cannot heal in the same environment that made you sick.', 303),
  ('Life is 10% what happens to you and 90% how you react to it.', 304),
  ('The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.', 305),
  ('An unexamined life is a journey through someone else''s map.', 306),
  ('The present moment is the only moment available to us, and it is the door to all moments.', 307),
  ('Kindness is a language which the deaf can hear and the blind can see.', 308),
  ('Fear is a reaction; courage is a decision.', 309),
  ('At the end of the day, we are all just walking each other home.', 310),
  ('Push yourself, because no one else is going to do it for you.', 311),
  ('Doubt kills more dreams than failure ever will.', 312),
  ('When you feel like quitting, remember why you started.', 313),
  ('Dream big, start small, act now.', 314),
  ('Consistency is the magic ingredient that turns average into exceptional.', 315),
  ('Your time is limited, so don''t waste it living someone else''s life.', 316),
  ('Courage is resistance to fear, mastery of fear, not absence of fear.', 317),
  ('Don''t let yesterday take up too much of today.', 318),
  ('You are stronger than you think and capable of more than you know.', 319),
  ('Turn your wounds into wisdom and your obstacles into fuel.', 320),
  ('Every champion was once a contender that refused to give up.', 321),
  ('The expert in anything was once a beginner.', 322),
  ('Hard days are the days that build your character the most.', 323),
  ('Make each day your masterpiece.', 324),
  ('Don''t wait for opportunity; create it with your preparation.', 325),
  ('Focus on progress, not perfection.', 326),
  ('Believe you can and you''re halfway there.', 327),
  ('The only person you should try to be better than is the person you were yesterday.', 328),
  ('Your mindset determines your horizon.', 329),
  ('One day or day one: you decide.', 330),
  ('Greatness is not in where we stand, but in what direction we are moving.', 331),
  ('Today''s struggles are tomorrow''s strengths.', 332),
  ('Never let the fear of striking out keep you from playing the game.', 333),
  ('If you believe it will work out, you''ll see opportunities; if you believe it won''t, you''ll see obstacles.', 334),
  ('Small shifts in daily habits compound into massive transformations.', 335),
  ('The man on top of the mountain didn''t fall there.', 336),
  ('Success is walking from failure to failure with no loss of enthusiasm.', 337),
  ('Don''t be afraid to give up the good to go for the great.', 338),
  ('Act as if what you do makes a difference; it does.', 339),
  ('You miss 100% of the shots you don''t take.', 340),
  ('An ounce of action is worth a ton of theory.', 341),
  ('If you want peace, prepare for understanding.', 342),
  ('Guard your attention like your most valuable currency.', 343),
  ('In a world full of noise, quiet confidence is revolutionary.', 344),
  ('Not every thought in your head deserves a microphone.', 345),
  ('You can''t outrun your shadow, but you can turn toward the sun.', 346),
  ('The easiest person to fool is yourself.', 347),
  ('True wealth is having things money cannot buy.', 348),
  ('The grass is greener where you water it.', 349),
  ('Life shrinks or expands in proportion to one''s courage.', 350),
  ('The fire that warms can also burn; temperance is mastery.', 351),
  ('We build too many walls and not enough bridges.', 352),
  ('You don''t have to win every argument to win at life.', 353),
  ('A good question is worth a hundred easy answers.', 354),
  ('Happiness is an inside job; don''t outsource it.', 355),
  ('When you change the way you look at things, the things you look at change.', 356),
  ('Don''t let compliments get to your head or criticism get to your heart.', 357),
  ('If you want to go fast, go alone; if you want to go far, go together.', 358),
  ('Today is the tomorrow you worried about yesterday.', 359),
  ('The greatest discovery of all time is that a person can alter their future by altering their attitude.', 360),
  ('Slow down to speed up.', 361),
  ('When in doubt, choose the path that makes for a better story.', 362),
  ('You cannot control the wind, but you can adjust your sails.', 363),
  ('Let your character speak so loudly that people don''t hear rumors.', 364),
  ('The only true wisdom is in knowing you know nothing.', 365),
  ('Life is either a daring adventure or nothing at all.', 366),
  ('What matters most is how well you walk through the fire.', 367),
  ('To lead yourself, use your head; to lead others, use your heart.', 368),
  ('Every moment is a fresh beginning disguised as the ordinary.', 369),
  ('Leave every room a little brighter than you found it.', 370)
ON CONFLICT (question) DO NOTHING;
